/**
 * lib/generation/audio-router.ts
 *
 * Multi-provider TTS generation with R2 storage, fallback chain,
 * budget enforcement, voice ID passthrough, and ledger integration.
 *
 * Key invariants:
 *  - R2 provisioning checked FIRST — same invariant as image-router.
 *  - selectModel() gates on budget before any provider API call.
 *  - Generated audio always stored in company R2 bucket — provider URLs never returned.
 *  - Duration estimated from text length (providers do not return duration).
 *    Formula: ceil(text.length / 12.5) seconds at ~150 wpm.
 *  - voiceId is passed through to providers that support clones (ElevenLabs, Cartesia).
 *  - AudioUploadError re-thrown immediately — not swallowed by fallback chain.
 */

import { createHash } from "node:crypto";
import OpenAI from "openai";
import { selectModel, getEstimatedCost } from "@/lib/generation/cost-optimizer";
import type { QualityTier } from "@/lib/generation/cost-optimizer";
import { getStatus } from "@/lib/provisioning/r2-provisioner";
import { R2NotProvisionedError } from "@/lib/generation/image-router";
import { checkModeration, ModerationBlockedError } from "@/lib/generation/moderation-filter";
import { store } from "@/lib/store";

// ── Provider interface ────────────────────────────────────────────────────────

export interface AudioProvider {
  readonly provider: string;
  readonly model: string;
  generate(req: AudioProviderRequest): Promise<AudioProviderResponse>;
}

export type AudioProviderRequest = {
  text: string;
  /** Per-company voice clone ID. Providers that don't support clones ignore this. */
  voiceId?: string;
  speed: number;
  format: "mp3" | "wav";
};

export type AudioProviderResponse = {
  audioData: Buffer;
  format: "mp3" | "wav";
};

// ── R2 storage interface (same shape as image-router) ─────────────────────────

export interface R2StorageClient {
  upload(input: {
    bucketName: string;
    key: string;
    data: Buffer;
    contentType: string;
  }): Promise<{ url: string }>;
}

// ── Public types ──────────────────────────────────────────────────────────────

export type AudioGenerationRequest = {
  companyId: string;
  qualityTier: QualityTier;
  /** The text to convert to speech. */
  text: string;
  /** Per-company voice clone ID. Injected by voice-memory.ts (Phase 4 build item 5). */
  voiceId?: string;
  /** Playback speed multiplier. Defaults to 1.0. Range: 0.5–2.0. */
  speed?: number;
  format?: "mp3" | "wav";
  description: string;
};

export type AudioGenerationResult = {
  /** Permanent CDN URL in the company's R2 bucket. */
  r2Url: string;
  provider: string;
  model: string;
  qualityTier: QualityTier;
  /** Always a positive integer (duration-based pricing). */
  actualCostCents: number;
  /** SHA-256 of generation inputs. For fingerprint-cache.ts (build item 7). */
  fingerprint: string;
  format: "mp3" | "wav";
  /** Estimated audio duration in seconds (derived from text length). */
  durationSeconds: number;
};

export type AudioRouterOptions = {
  providers?: AudioProvider[];
  r2Client?: R2StorageClient;
  /**
   * Override R2 provisioned resource lookup.
   * - `undefined`: calls getStatus(companyId) from r2-provisioner
   * - explicit value (including `null`): used directly (for testing)
   */
  r2ProvisionedResource?: import("@/lib/provisioning/r2-provisioner").R2ProvisionedResource | null;
};

// ── Error types ───────────────────────────────────────────────────────────────

export class AllProvidersFailedError extends Error {
  constructor(
    readonly qualityTier: QualityTier,
    readonly attempts: Array<{ provider: string; model: string; error: string }>
  ) {
    const summary = attempts.map(a => `${a.provider}/${a.model}: ${a.error}`).join("; ");
    super(`All audio providers failed for ${qualityTier} quality. Attempts: [${summary}]`);
    this.name = "AllProvidersFailedError";
  }
}

export class AudioUploadError extends Error {
  constructor(
    readonly provider: string,
    readonly model: string,
    cause: string
  ) {
    super(`Audio generated by ${provider}/${model} but R2 upload failed: ${cause}`);
    this.name = "AudioUploadError";
  }
}

// ── Fallback chain ────────────────────────────────────────────────────────────

type ProviderConfig = { provider: string; model: string; client: "openai" | "elevenlabs" };

const AUDIO_FALLBACK_CHAIN: Record<QualityTier, ProviderConfig[]> = {
  draft: [
    { provider: "openai",     model: "tts-1",             client: "openai"     },
  ],
  standard: [
    { provider: "elevenlabs", model: "eleven_turbo_v2",   client: "elevenlabs" },
    { provider: "openai",     model: "tts-1-hd",          client: "openai"     },
  ],
  premium: [
    { provider: "elevenlabs", model: "eleven_v2_flash",   client: "elevenlabs" },
    { provider: "openai",     model: "tts-1-hd",          client: "openai"     },
  ],
};

// ── Real provider implementations ─────────────────────────────────────────────

const OPENAI_VOICES = ["alloy", "echo", "fable", "onyx", "nova", "shimmer"] as const;
type OpenAIVoice = typeof OPENAI_VOICES[number];

class OpenAIAudioProvider implements AudioProvider {
  readonly provider = "openai";
  readonly model: string;
  private client: OpenAI;

  constructor(model: string) {
    this.model  = model;
    this.client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY ?? "", timeout: 30_000 });
  }

  async generate(req: AudioProviderRequest): Promise<AudioProviderResponse> {
    const voice: OpenAIVoice =
      req.voiceId && (OPENAI_VOICES as readonly string[]).includes(req.voiceId)
        ? (req.voiceId as OpenAIVoice)
        : "alloy";

    const response = await this.client.audio.speech.create({
      model:           this.model,
      voice,
      input:           req.text,
      response_format: req.format === "wav" ? "wav" : "mp3",
      speed:           req.speed,
    });

    const buffer = Buffer.from(await response.arrayBuffer());
    return { audioData: buffer, format: req.format };
  }
}

class ElevenLabsAudioProvider implements AudioProvider {
  readonly provider = "elevenlabs";
  readonly model: string;
  private readonly defaultVoiceId = "21m00Tcm4TlvDq8ikWAM"; // Rachel (ElevenLabs default)

  constructor(model: string) {
    this.model = model;
  }

  async generate(req: AudioProviderRequest): Promise<AudioProviderResponse> {
    const voiceId = req.voiceId ?? this.defaultVoiceId;
    const apiKey  = process.env.ELEVENLABS_API_KEY ?? "";

    const res = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
      {
        method:  "POST",
        headers: {
          "Content-Type": "application/json",
          "xi-api-key":   apiKey,
        },
        body: JSON.stringify({
          text:           req.text,
          model_id:       this.model,
          voice_settings: { stability: 0.5, similarity_boost: 0.75 },
        }),
        signal: AbortSignal.timeout(30_000),
      }
    );

    if (!res.ok) throw new Error(`ElevenLabs HTTP ${res.status}: ${await res.text()}`);
    return {
      audioData: Buffer.from(await res.arrayBuffer()),
      format:    "mp3",
    };
  }
}

function createDefaultProviders(qualityTier: QualityTier): AudioProvider[] {
  return AUDIO_FALLBACK_CHAIN[qualityTier].map(cfg =>
    cfg.client === "openai"
      ? new OpenAIAudioProvider(cfg.model)
      : new ElevenLabsAudioProvider(cfg.model)
  );
}

// ── Default R2 client (stub) ───────────────────────────────────────────────────

class DefaultR2StorageClient implements R2StorageClient {
  async upload(_input: {
    bucketName: string; key: string; data: Buffer; contentType: string;
  }): Promise<{ url: string }> {
    throw new Error(
      "R2StorageClient not configured. Provide via AudioRouterOptions.r2Client."
    );
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function estimateDuration(text: string): number {
  // ~150 wpm × ~5 chars/word = ~12.5 chars/sec. Minimum 1 second.
  return Math.max(1, Math.ceil(text.length / 12.5));
}

function computeFingerprint(
  text: string,
  voiceId: string | undefined,
  speed: number,
  format: string,
  model: string,
): string {
  const data = JSON.stringify({
    text,
    voiceId: voiceId ?? null,
    speed,
    format,
    model,
  });
  return createHash("sha256").update(data).digest("hex");
}

function contentType(format: "mp3" | "wav"): string {
  return format === "wav" ? "audio/wav" : "audio/mpeg";
}

// ── generateAudio ─────────────────────────────────────────────────────────────

export async function generateAudio(
  req: AudioGenerationRequest,
  options?: AudioRouterOptions
): Promise<AudioGenerationResult> {
  const speed          = req.speed  ?? 1.0;
  const format         = req.format ?? "mp3";
  const durationSeconds = estimateDuration(req.text);

  // 1. Check R2 provisioning FIRST
  const r2Resource = "r2ProvisionedResource" in (options ?? {})
    ? options!.r2ProvisionedResource
    : await getStatus(req.companyId);

  if (!r2Resource) throw new R2NotProvisionedError(req.companyId);

  // 2. Moderation check — blocked text must never reach a generation provider.
  const modResult = checkModeration(req.text, "audio");
  if (modResult.verdict === "block") {
    throw new ModerationBlockedError(modResult);
  }

  // 3. Budget check + model selection
  const selection = await selectModel({
    companyId:      req.companyId,
    taskType:       "audio",
    qualityTier:    req.qualityTier,
    estimatedUnits: durationSeconds,
    description:    req.description,
  });

  // 4. Compute input fingerprint
  const fingerprint = computeFingerprint(
    req.text,
    req.voiceId,
    speed,
    format,
    selection.model,
  );

  // 5. Try each provider in order
  const providers = options?.providers ?? createDefaultProviders(req.qualityTier);
  const r2Client  = options?.r2Client  ?? new DefaultR2StorageClient();
  const attempts: Array<{ provider: string; model: string; error: string }> = [];

  for (const p of providers) {
    try {
      const response = await p.generate({
        text:    req.text,
        voiceId: req.voiceId,
        speed,
        format,
      });

      if (!response.audioData.length) {
        attempts.push({ provider: p.provider, model: p.model, error: "empty audio data" });
        continue;
      }

      // 6. Upload to R2
      const ext = response.format;
      const key = `audio/${fingerprint.slice(0, 16)}/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;
      let r2Url: string;
      try {
        const uploaded = await r2Client.upload({
          bucketName:  r2Resource.bucketName,
          key,
          data:        response.audioData,
          contentType: contentType(response.format),
        });
        r2Url = uploaded.url;
      } catch (uploadErr) {
        throw new AudioUploadError(
          p.provider,
          p.model,
          uploadErr instanceof Error ? uploadErr.message : String(uploadErr)
        );
      }

      // 7. Write actual cost to "media" ledger
      const actualCostCents = Math.round(getEstimatedCost("audio", req.qualityTier, durationSeconds));

      await store.addUsage({
        companyId:   req.companyId,
        category:    "media",
        description: req.description,
        amountCents: actualCostCents,
        metadata: {
          provider:        p.provider,
          model:           p.model,
          qualityTier:     req.qualityTier,
          fingerprint,
          r2Url,
          format:          response.format,
          durationSeconds,
        },
      });

      return {
        r2Url,
        provider:        p.provider,
        model:           p.model,
        qualityTier:     req.qualityTier,
        actualCostCents,
        fingerprint,
        format:          response.format,
        durationSeconds,
      };
    } catch (err) {
      if (err instanceof AudioUploadError || err instanceof R2NotProvisionedError) throw err;

      attempts.push({
        provider: p.provider,
        model:    p.model,
        error:    err instanceof Error ? err.message : String(err),
      });
    }
  }

  throw new AllProvidersFailedError(req.qualityTier, attempts);
}
