/**
 * lib/generation/image-router.ts
 *
 * Multi-provider image generation with R2 storage, fallback chain,
 * budget enforcement, visual context injection, and ledger integration.
 *
 * Key invariants:
 *  - R2 provisioning checked FIRST — never generate if we cannot store the asset.
 *  - selectModel() gates on budget before any provider API call.
 *  - Generated images always stored in company R2 bucket — provider URLs never returned.
 *  - Providers return Buffer directly — no provider URL escapes this module.
 *  - Fingerprint computed from inputs only — image bytes do not affect it.
 *  - Every successful generation writes a "media" ledger entry.
 *  - R2 upload failure after generation throws ImageUploadError (no ledger entry written).
 */

import { createHash } from "node:crypto";
import OpenAI from "openai";
import { selectModel, getEstimatedCost } from "@/lib/generation/cost-optimizer";
import type { QualityTier } from "@/lib/generation/cost-optimizer";
import { checkModeration, ModerationBlockedError } from "@/lib/generation/moderation-filter";
import { getStatus } from "@/lib/provisioning/r2-provisioner";
import type { R2ProvisionedResource } from "@/lib/provisioning/r2-provisioner";
import { store } from "@/lib/store";

// ── Provider interface ────────────────────────────────────────────────────────

export interface ImageProvider {
  readonly provider: string;
  readonly model: string;
  generate(req: ImageProviderRequest): Promise<ImageProviderResponse>;
}

export type ImageProviderRequest = {
  prompt: string;
  negativePrompt?: string;
  width: number;
  height: number;
};

export type ImageProviderResponse = {
  /** Raw image bytes. Real providers download from temporary URL before returning. */
  imageData: Buffer;
  format: "png" | "jpeg" | "webp";
};

// ── R2 storage interface ──────────────────────────────────────────────────────

export interface R2StorageClient {
  upload(input: {
    bucketName: string;
    key: string;
    data: Buffer;
    contentType: string;
  }): Promise<{ url: string }>;
}

// ── Public types ──────────────────────────────────────────────────────────────

export type ImageGenerationRequest = {
  companyId: string;
  qualityTier: QualityTier;
  prompt: string;
  negativePrompt?: string;
  /** Injected by visual-memory.ts (Phase 4 build item 6). Appended to prompt. */
  visualContext?: { positivePrompt?: string; negativePrompt?: string };
  width?: number;
  height?: number;
  description: string;
};

export type ImageGenerationResult = {
  /** Permanent CDN URL in the company's R2 bucket. */
  r2Url: string;
  provider: string;
  model: string;
  qualityTier: QualityTier;
  /** Always a positive integer (per-image pricing). */
  actualCostCents: number;
  /** SHA-256 of generation inputs. For fingerprint-cache.ts lookup (build item 7). */
  fingerprint: string;
  format: "png" | "jpeg" | "webp";
};

export type ImageRouterOptions = {
  providers?: ImageProvider[];
  r2Client?: R2StorageClient;
  /**
   * Override R2 provisioned resource lookup.
   * - `undefined` (not provided): calls getStatus(companyId) from r2-provisioner
   * - explicit value (including `null`): uses that value directly (for testing)
   */
  r2ProvisionedResource?: R2ProvisionedResource | null;
};

// ── Error types ───────────────────────────────────────────────────────────────

export class AllProvidersFailedError extends Error {
  constructor(
    readonly qualityTier: QualityTier,
    readonly attempts: Array<{ provider: string; model: string; error: string }>
  ) {
    const summary = attempts.map(a => `${a.provider}/${a.model}: ${a.error}`).join("; ");
    super(`All image providers failed for ${qualityTier} quality. Attempts: [${summary}]`);
    this.name = "AllProvidersFailedError";
  }
}

export class R2NotProvisionedError extends Error {
  constructor(readonly companyId: string) {
    super(
      `Company ${companyId} has no R2 bucket provisioned. ` +
      `Run /provision-company to set up storage before generating images.`
    );
    this.name = "R2NotProvisionedError";
  }
}

export class ImageUploadError extends Error {
  constructor(
    readonly provider: string,
    readonly model: string,
    cause: string
  ) {
    super(`Image generated by ${provider}/${model} but R2 upload failed: ${cause}`);
    this.name = "ImageUploadError";
  }
}

// ── Fallback chain ────────────────────────────────────────────────────────────

type ProviderConfig = { provider: string; model: string; client: "openai" | "together" };

const IMAGE_FALLBACK_CHAIN: Record<QualityTier, ProviderConfig[]> = {
  draft: [
    { provider: "openrouter", model: "black-forest-labs/FLUX.1-schnell", client: "together" },
    { provider: "openrouter", model: "stability-ai/sdxl",                client: "together" },
  ],
  standard: [
    { provider: "openai",     model: "dall-e-3",                         client: "openai"   },
    { provider: "openrouter", model: "black-forest-labs/FLUX.1-dev",     client: "together" },
  ],
  premium: [
    { provider: "openai",     model: "dall-e-3-hd",                      client: "openai"   },
    { provider: "openrouter", model: "black-forest-labs/FLUX.1-pro",     client: "together" },
  ],
};

// ── Real provider implementations ─────────────────────────────────────────────

class OpenAIImageProvider implements ImageProvider {
  readonly provider = "openai";
  readonly model: string;
  private client: OpenAI;

  constructor(model: string) {
    this.model  = model;
    this.client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY ?? "", timeout: 60_000 });
  }

  async generate(req: ImageProviderRequest): Promise<ImageProviderResponse> {
    const response = await this.client.images.generate({
      model:           this.model,
      prompt:          req.prompt,
      n:               1,
      size:            "1024x1024",
      response_format: "url",
    });
    const url = response.data?.[0]?.url;
    if (!url) return { imageData: Buffer.alloc(0), format: "png" };

    const imgRes = await fetch(url);
    return {
      imageData: Buffer.from(await imgRes.arrayBuffer()),
      format:    "png",
    };
  }
}

class TogetherAIImageProvider implements ImageProvider {
  readonly provider: string;
  readonly model: string;
  private client: OpenAI;

  constructor(provider: string, model: string) {
    this.provider = provider;
    this.model    = model;
    this.client   = new OpenAI({
      apiKey:  process.env.TOGETHER_API_KEY ?? "",
      baseURL: "https://api.together.xyz/v1",
      timeout: 60_000,
    });
  }

  async generate(req: ImageProviderRequest): Promise<ImageProviderResponse> {
    const response = await this.client.images.generate({
      model:  this.model,
      prompt: req.prompt,
      n:      1,
    });
    const b64 = response.data?.[0]?.b64_json;
    const url = response.data?.[0]?.url;

    if (b64) return { imageData: Buffer.from(b64, "base64"), format: "png" };
    if (url) {
      const imgRes = await fetch(url);
      return { imageData: Buffer.from(await imgRes.arrayBuffer()), format: "png" };
    }
    return { imageData: Buffer.alloc(0), format: "png" };
  }
}

function createDefaultProviders(qualityTier: QualityTier): ImageProvider[] {
  return IMAGE_FALLBACK_CHAIN[qualityTier].map(cfg =>
    cfg.client === "openai"
      ? new OpenAIImageProvider(cfg.model)
      : new TogetherAIImageProvider(cfg.provider, cfg.model)
  );
}

// ── Default R2 client (stub — requires @aws-sdk/client-s3 for production) ─────

class DefaultR2StorageClient implements R2StorageClient {
  async upload(_input: {
    bucketName: string; key: string; data: Buffer; contentType: string;
  }): Promise<{ url: string }> {
    throw new Error(
      "R2StorageClient not configured for production. " +
      "Provide a client via ImageRouterOptions.r2Client."
    );
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function computeFingerprint(
  prompt: string,
  negativePrompt: string | undefined,
  visualContext: ImageGenerationRequest["visualContext"],
  model: string,
  width: number,
  height: number,
): string {
  const data = JSON.stringify({
    prompt,
    negativePrompt:  negativePrompt  ?? null,
    visualContext:   visualContext   ?? null,
    model,
    width,
    height,
  });
  return createHash("sha256").update(data).digest("hex");
}

function contentType(format: "png" | "jpeg" | "webp"): string {
  return format === "jpeg" ? "image/jpeg" : format === "webp" ? "image/webp" : "image/png";
}

// ── generateImage ─────────────────────────────────────────────────────────────

export async function generateImage(
  req: ImageGenerationRequest,
  options?: ImageRouterOptions
): Promise<ImageGenerationResult> {
  const width  = req.width  ?? 1024;
  const height = req.height ?? 1024;

  // 1. Check R2 provisioning FIRST — no point generating if we can't store
  const r2Resource = "r2ProvisionedResource" in (options ?? {})
    ? options!.r2ProvisionedResource
    : await getStatus(req.companyId);

  if (!r2Resource) throw new R2NotProvisionedError(req.companyId);

  // 2. Build prompt, optionally appending visual context
  let prompt = req.prompt;
  if (req.visualContext?.positivePrompt) {
    prompt = `${prompt}, ${req.visualContext.positivePrompt}`;
  }

  // Build composite negative prompt
  const negativeParts: string[] = [];
  if (req.negativePrompt) negativeParts.push(req.negativePrompt);
  if (req.visualContext?.negativePrompt) negativeParts.push(req.visualContext.negativePrompt);
  const negativePrompt = negativeParts.length > 0 ? negativeParts.join(", ") : undefined;

  // 3. Moderation check — blocked prompts must never reach a generation provider.
  const modResult = checkModeration(
    [prompt, negativePrompt].filter(Boolean).join("\n"),
    "image"
  );
  if (modResult.verdict === "block") {
    throw new ModerationBlockedError(modResult);
  }

  // 4. Budget check + model selection (throws SpendCapExceededError / BudgetQualityConflictError)
  const selection = await selectModel({
    companyId:      req.companyId,
    taskType:       "image",
    qualityTier:    req.qualityTier,
    estimatedUnits: 1,
    description:    req.description,
  });

  // 4. Input fingerprint — computed before generation, independent of image bytes
  const fingerprint = computeFingerprint(
    req.prompt,
    req.negativePrompt,
    req.visualContext,
    selection.model,
    width,
    height,
  );

  // 5. Try each provider in order; skip on failure or empty image data
  const providers = options?.providers ?? createDefaultProviders(req.qualityTier);
  const r2Client  = options?.r2Client  ?? new DefaultR2StorageClient();
  const attempts: Array<{ provider: string; model: string; error: string }> = [];

  for (const p of providers) {
    try {
      const response = await p.generate({ prompt, negativePrompt, width, height });

      if (!response.imageData.length) {
        attempts.push({ provider: p.provider, model: p.model, error: "empty image data" });
        continue;
      }

      // 6. Upload to company R2 bucket
      const ext    = response.format;
      const key    = `images/${fingerprint.slice(0, 16)}/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;
      let r2Url: string;
      try {
        const uploaded = await r2Client.upload({
          bucketName:  r2Resource.bucketName,
          key,
          data:        response.imageData,
          contentType: contentType(response.format),
        });
        r2Url = uploaded.url;
      } catch (uploadErr) {
        throw new ImageUploadError(
          p.provider,
          p.model,
          uploadErr instanceof Error ? uploadErr.message : String(uploadErr)
        );
      }

      // 7. Write actual cost to "media" ledger entry (per-image pricing is already integer)
      const actualCostCents = Math.round(getEstimatedCost("image", req.qualityTier, 1));

      await store.addUsage({
        companyId:   req.companyId,
        category:    "media",
        description: req.description,
        amountCents: actualCostCents,
        metadata: {
          provider:    p.provider,
          model:       p.model,
          qualityTier: req.qualityTier,
          fingerprint,
          r2Url,
          format:      response.format,
        },
      });

      return {
        r2Url,
        provider:        p.provider,
        model:           p.model,
        qualityTier:     req.qualityTier,
        actualCostCents,
        fingerprint,
        format:          response.format,
      };
    } catch (err) {
      // Re-throw R2 and infrastructure errors immediately — don't try next provider
      if (err instanceof ImageUploadError || err instanceof R2NotProvisionedError) throw err;

      attempts.push({
        provider: p.provider,
        model:    p.model,
        error:    err instanceof Error ? err.message : String(err),
      });
    }
  }

  throw new AllProvidersFailedError(req.qualityTier, attempts);
}
