#!/usr/bin/env node
// gen-keys.mjs — generate the release signing keys in the formats the installers verify.
//
//   node scripts/installer/keys/gen-keys.mjs [--force]
//
// Writes, in this directory:
//   minisign.pub                    Ed25519 public key, minisign text format (COMMITTED)
//   minisign.key                    Ed25519 secret key, minisign format, unencrypted (GITIGNORED)
//   ecdsa-p256.pub.pem              ECDSA P-256 public key, SPKI PEM (COMMITTED)
//   ecdsa-p256.key.pem              ECDSA P-256 private key, PKCS#8 PEM (GITIGNORED)
//
// minisign is the canonical format (shared with `trent update` and `trent desktop install`);
// the ECDSA key exists only because stock macOS ships LibreSSL 3.3, which cannot verify
// Ed25519, and the POSIX installer must still verify on a bare Mac. See README.md.
//
// The formats follow minisign's documented layout so the real `minisign` tool interoperates:
//   public key : "Ed" || key_id(8, LE) || pk(32)
//   secret key : "Ed" "Sc" "B2" || kdf_salt(32) || opslimit(8) || memlimit(8)
//                || key_id(8) || sk(64) || blake2b-256("Ed" || key_id || sk)      (opslimit=memlimit=0: stored in clear)
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { blake2b } from "./blake2b.mjs";
import { existsSync, writeFileSync, chmodSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const force = process.argv.includes("--force");
const out = (name) => join(here, name);
for (const f of ["minisign.pub", "minisign.key", "ecdsa-p256.pub.pem", "ecdsa-p256.key.pem"]) {
  if (existsSync(out(f)) && !force) { console.error(`refusing to overwrite ${f} (pass --force)`); process.exit(1); }
}

// ---- Ed25519 in minisign format
const ed = generateKeyPairSync("ed25519");
const seed = Buffer.from(ed.privateKey.export({ format: "jwk" }).d, "base64url");
const pk = Buffer.from(ed.publicKey.export({ format: "jwk" }).x, "base64url");
if (seed.length !== 32 || pk.length !== 32) throw new Error("unexpected ed25519 key sizes");
const keyId = randomBytes(8);
const sk = Buffer.concat([seed, pk]);
const keyIdHex = Buffer.from(keyId).reverse().toString("hex").toUpperCase(); // minisign prints the LE u64 as hex

const pubBlob = Buffer.concat([Buffer.from("Ed"), keyId, pk]);
const pubText = `untrusted comment: minisign public key ${keyIdHex}\n${pubBlob.toString("base64")}\n`;

// minisign checks this on load: BLAKE2b-256 of sig_alg || key_id || sk.
const chk = blake2b(Buffer.concat([Buffer.from("Ed"), keyId, sk]), 32);
const secBlob = Buffer.concat([
  Buffer.from("Ed"), Buffer.from("Sc"), Buffer.from("B2"),
  Buffer.alloc(32), Buffer.alloc(8), Buffer.alloc(8),
  keyId, sk, chk,
]);
const secText = `untrusted comment: minisign secret key (unencrypted, generated by gen-keys.mjs)\n${secBlob.toString("base64")}\n`;

// ---- ECDSA P-256 (LibreSSL-verifiable co-signing key)
const ec = generateKeyPairSync("ec", { namedCurve: "prime256v1" });
const ecPub = ec.publicKey.export({ type: "spki", format: "pem" });
const ecKey = ec.privateKey.export({ type: "pkcs8", format: "pem" });

writeFileSync(out("minisign.pub"), pubText);
writeFileSync(out("minisign.key"), secText, { mode: 0o600 }); chmodSync(out("minisign.key"), 0o600);
writeFileSync(out("ecdsa-p256.pub.pem"), ecPub);
writeFileSync(out("ecdsa-p256.key.pem"), ecKey, { mode: 0o600 }); chmodSync(out("ecdsa-p256.key.pem"), 0o600);
console.log(`wrote minisign.pub (key id ${keyIdHex}) and ecdsa-p256.pub.pem; private keys are gitignored`);
