// Agent Plug catalog — sourced from https://github.com/msitarzewski/agency-agents
// 164 specialists across 13 non-game divisions
import { assertSkillsInstalled, resolveSkillsForAgent } from "@/lib/agent-skills";
import type { EvalTask } from "@/lib/plug-evals";
import type { AgentEnvironmentConfig, AgentQualityLabel, AgentRole } from "@/lib/types";

export type CatalogCategory =
  | "engineering"
  | "design"
  | "paid-media"
  | "sales"
  | "marketing"
  | "product"
  | "project-management"
  | "testing"
  | "support"
  | "finance"
  | "spatial-computing"
  | "academic"
  | "specialized";

export type CatalogAgent = {
  id: string;
  name: string;
  emoji: string;
  category: CatalogCategory;
  specialties: string;
  whenToUse: string;
  whenNotToUse?: string;
  modelPolicy?: "reasoning-heavy" | "balanced" | "fast";
  specialistPrompt?: string;
  designedTools?: Array<{
    name: string;
    purpose: string;
    composio?: { toolkit: string; action: string } | null;
  }>;
  reversibilityMatrix?: {
    reversible: string[];
    costlyToReverse: string[];
    irreversible: string[];
  };
  memoryPlan?: {
    readsOnStart: string[];
    writesOnFinish: string[];
  };
  /** v3: skills this agent should run with. Resolved from skill-agent-map.json. */
  skills?: string[];
  evalSuite?: {
    capability: Array<string | EvalTask>;
    regression: Array<string | EvalTask>;
  };
  capability?: {
    score: number | null;
    qualityLabel: AgentQualityLabel;
  };
  color: string; // hex or css color for accent
  file: string;  // relative path in agency-agents repo
};

export const AGENT_CATALOG: CatalogAgent[] = [
  // ── Engineering ──────────────────────────────────────────────────────────
  {
    id: "eng-ai-data-remediation-engineer",
    name: "AI Data Remediation Engineer",
    emoji: "🧬",
    category: "engineering",
    specialties: "Self-healing pipelines, air-gapped SLMs, semantic clustering",
    whenToUse: "Fixing broken data at scale with zero data loss",
    color: "#06B6D4",
    file: "engineering/engineering-ai-data-remediation-engineer.md",
  },
  {
    id: "eng-ai-engineer",
    name: "AI Engineer",
    emoji: "🤖",
    category: "engineering",
    specialties: "ML models, deployment, AI integration",
    whenToUse: "Machine learning features, data pipelines, AI-powered apps",
    color: "#06B6D4",
    file: "engineering/engineering-ai-engineer.md",
  },
  {
    id: "eng-autonomous-optimization-architect",
    name: "Autonomous Optimization Architect",
    emoji: "⚡",
    category: "engineering",
    specialties: "LLM routing, cost optimization, shadow testing",
    whenToUse: "Autonomous systems needing intelligent API selection and cost guardrails",
    color: "#673AB7",
    file: "engineering/engineering-autonomous-optimization-architect.md",
  },
  {
    id: "eng-backend-architect",
    name: "Backend Architect",
    emoji: "🏗️",
    category: "engineering",
    specialties: "API design, database architecture, scalability",
    whenToUse: "Server-side systems, microservices, cloud infrastructure",
    color: "#06B6D4",
    file: "engineering/engineering-backend-architect.md",
  },
  {
    id: "eng-cms-developer",
    name: "CMS Developer",
    emoji: "🧱",
    category: "engineering",
    specialties: "WordPress & Drupal themes, plugins/modules, content architecture",
    whenToUse: "Code-first CMS implementation and customization",
    color: "#06B6D4",
    file: "engineering/engineering-cms-developer.md",
  },
  {
    id: "eng-code-reviewer",
    name: "Code Reviewer",
    emoji: "👁️",
    category: "engineering",
    specialties: "Constructive code review, security, maintainability",
    whenToUse: "PR reviews, code quality gates, mentoring through review",
    color: "#06B6D4",
    file: "engineering/engineering-code-reviewer.md",
  },
  {
    id: "eng-codebase-onboarding-engineer",
    name: "Codebase Onboarding Engineer",
    emoji: "🧭",
    category: "engineering",
    specialties: "Fast developer onboarding, read-only codebase exploration, factual explanation",
    whenToUse: "Helping new developers understand unfamiliar repos quickly by reading the code, tracing code paths, and stating facts about structure and behavior",
    color: "#06B6D4",
    file: "engineering/engineering-codebase-onboarding-engineer.md",
  },
  {
    id: "eng-data-engineer",
    name: "Data Engineer",
    emoji: "🔧",
    category: "engineering",
    specialties: "Data pipelines, lakehouse architecture, ETL/ELT",
    whenToUse: "Building reliable data infrastructure and warehousing",
    color: "#06B6D4",
    file: "engineering/engineering-data-engineer.md",
  },
  {
    id: "eng-database-optimizer",
    name: "Database Optimizer",
    emoji: "🗄️",
    category: "engineering",
    specialties: "Schema design, query optimization, indexing strategies",
    whenToUse: "PostgreSQL/MySQL tuning, slow query debugging, migration planning",
    color: "#06B6D4",
    file: "engineering/engineering-database-optimizer.md",
  },
  {
    id: "eng-devops-automator",
    name: "DevOps Automator",
    emoji: "⚙️",
    category: "engineering",
    specialties: "CI/CD, infrastructure automation, cloud ops",
    whenToUse: "Pipeline development, deployment automation, monitoring",
    color: "#06B6D4",
    file: "engineering/engineering-devops-automator.md",
  },
  {
    id: "eng-email-intelligence-engineer",
    name: "Email Intelligence Engineer",
    emoji: "📧",
    category: "engineering",
    specialties: "Email parsing, MIME extraction, structured data for AI agents",
    whenToUse: "Turning raw email threads into reasoning-ready context",
    color: "#06B6D4",
    file: "engineering/engineering-email-intelligence-engineer.md",
  },
  {
    id: "eng-embedded-firmware-engineer",
    name: "Embedded Firmware Engineer",
    emoji: "🔩",
    category: "engineering",
    specialties: "Bare-metal, RTOS, ESP32/STM32/Nordic firmware",
    whenToUse: "Production-grade embedded systems and IoT devices",
    color: "#06B6D4",
    file: "engineering/engineering-embedded-firmware-engineer.md",
  },
  {
    id: "eng-feishu-integration-developer",
    name: "Feishu Integration Developer",
    emoji: "🔗",
    category: "engineering",
    specialties: "Feishu/Lark Open Platform, bots, workflows",
    whenToUse: "Building integrations for the Feishu ecosystem",
    color: "#06B6D4",
    file: "engineering/engineering-feishu-integration-developer.md",
  },
  {
    id: "eng-filament-optimization-specialist",
    name: "Filament Optimization Specialist",
    emoji: "🔧",
    category: "engineering",
    specialties: "Filament PHP admin UX, structural form redesign, resource optimization",
    whenToUse: "Restructuring Filament resources/forms/tables for faster, cleaner admin workflows",
    color: "#06B6D4",
    file: "engineering/engineering-filament-optimization-specialist.md",
  },
  {
    id: "eng-frontend-developer",
    name: "Frontend Developer",
    emoji: "🖥️",
    category: "engineering",
    specialties: "React/Vue/Angular, UI implementation, performance",
    whenToUse: "Modern web apps, pixel-perfect UIs, Core Web Vitals optimization",
    color: "#06B6D4",
    file: "engineering/engineering-frontend-developer.md",
  },
  {
    id: "eng-git-workflow-master",
    name: "Git Workflow Master",
    emoji: "🌿",
    category: "engineering",
    specialties: "Branching strategies, conventional commits, advanced Git",
    whenToUse: "Git workflow design, history cleanup, CI-friendly branch management",
    color: "#06B6D4",
    file: "engineering/engineering-git-workflow-master.md",
  },
  {
    id: "eng-incident-response-commander",
    name: "Incident Response Commander",
    emoji: "🚨",
    category: "engineering",
    specialties: "Incident management, post-mortems, on-call",
    whenToUse: "Managing production incidents and building incident readiness",
    color: "#e63946",
    file: "engineering/engineering-incident-response-commander.md",
  },
  {
    id: "eng-minimal-change-engineer",
    name: "Minimal Change Engineer",
    emoji: "🪡",
    category: "engineering",
    specialties: "Engineering specialist focused on minimum-viable diffs — fixes only what was asked, refuses scope creep, prefers three similar lines over a premature abstraction. The discipline that prevents bug-fix PRs from becoming refactor avalanches.",
    whenToUse: "The smallest diff that solves the problem — every extra line is a liability.",
    color: "#06B6D4",
    file: "engineering/engineering-minimal-change-engineer.md",
  },
  {
    id: "eng-mobile-app-builder",
    name: "Mobile App Builder",
    emoji: "📲",
    category: "engineering",
    specialties: "iOS/Android, React Native, Flutter",
    whenToUse: "Native and cross-platform mobile applications",
    color: "#06B6D4",
    file: "engineering/engineering-mobile-app-builder.md",
  },
  {
    id: "eng-rapid-prototyper",
    name: "Rapid Prototyper",
    emoji: "⚡",
    category: "engineering",
    specialties: "Fast POC development, MVPs",
    whenToUse: "Quick proof-of-concepts, hackathon projects, fast iteration",
    color: "#06B6D4",
    file: "engineering/engineering-rapid-prototyper.md",
  },
  {
    id: "eng-security-engineer",
    name: "Security Engineer",
    emoji: "🔒",
    category: "engineering",
    specialties: "Threat modeling, secure code review, security architecture",
    whenToUse: "Application security, vulnerability assessment, security CI/CD",
    color: "#06B6D4",
    file: "engineering/engineering-security-engineer.md",
  },
  {
    id: "eng-senior-developer",
    name: "Senior Developer",
    emoji: "💎",
    category: "engineering",
    specialties: "Laravel/Livewire, advanced patterns",
    whenToUse: "Complex implementations, architecture decisions",
    color: "#06B6D4",
    file: "engineering/engineering-senior-developer.md",
  },
  {
    id: "eng-software-architect",
    name: "Software Architect",
    emoji: "🏛️",
    category: "engineering",
    specialties: "System design, DDD, architectural patterns, trade-off analysis",
    whenToUse: "Architecture decisions, domain modeling, system evolution strategy",
    color: "#06B6D4",
    file: "engineering/engineering-software-architect.md",
  },
  {
    id: "eng-solidity-smart-contract-engineer",
    name: "Solidity Smart Contract Engineer",
    emoji: "⛓️",
    category: "engineering",
    specialties: "EVM contracts, gas optimization, DeFi",
    whenToUse: "Secure, gas-optimized smart contracts and DeFi protocols",
    color: "#06B6D4",
    file: "engineering/engineering-solidity-smart-contract-engineer.md",
  },
  {
    id: "eng-sre",
    name: "SRE",
    emoji: "🛡️",
    category: "engineering",
    specialties: "SLOs, error budgets, observability, chaos engineering",
    whenToUse: "Production reliability, toil reduction, capacity planning",
    color: "#e63946",
    file: "engineering/engineering-sre.md",
  },
  {
    id: "eng-technical-writer",
    name: "Technical Writer",
    emoji: "📚",
    category: "engineering",
    specialties: "Developer docs, API reference, tutorials",
    whenToUse: "Clear, accurate technical documentation",
    color: "#06B6D4",
    file: "engineering/engineering-technical-writer.md",
  },
  {
    id: "eng-threat-detection-engineer",
    name: "Threat Detection Engineer",
    emoji: "🎯",
    category: "engineering",
    specialties: "SIEM rules, threat hunting, ATT&CK mapping",
    whenToUse: "Building detection layers and threat hunting",
    color: "#7b2d8e",
    file: "engineering/engineering-threat-detection-engineer.md",
  },
  {
    id: "eng-voice-ai-integration-engineer",
    name: "Voice AI Integration Engineer",
    emoji: "🎙️",
    category: "engineering",
    specialties: "Speech-to-text pipelines, Whisper, ASR, speaker diarization",
    whenToUse: "End-to-end transcription pipelines, audio preprocessing, structured transcript delivery",
    color: "#06B6D4",
    file: "engineering/engineering-voice-ai-integration-engineer.md",
  },
  {
    id: "eng-wechat-mini-program-developer",
    name: "WeChat Mini Program Developer",
    emoji: "💬",
    category: "engineering",
    specialties: "WeChat ecosystem, Mini Programs, payment integration",
    whenToUse: "Building performant apps for the WeChat ecosystem",
    color: "#06B6D4",
    file: "engineering/engineering-wechat-mini-program-developer.md",
  },
  // ── Design ──────────────────────────────────────────────────────────
  {
    id: "design-brand-guardian",
    name: "Brand Guardian",
    emoji: "🎨",
    category: "design",
    specialties: "Brand identity, consistency, positioning",
    whenToUse: "Brand strategy, identity development, guidelines",
    color: "#EC4899",
    file: "design/design-brand-guardian.md",
  },
  {
    id: "design-image-prompt-engineer",
    name: "Image Prompt Engineer",
    emoji: "📷",
    category: "design",
    specialties: "AI image generation prompts, photography",
    whenToUse: "Photography prompts for Midjourney, DALL-E, Stable Diffusion",
    color: "#EC4899",
    file: "design/design-image-prompt-engineer.md",
  },
  {
    id: "design-inclusive-visuals-specialist",
    name: "Inclusive Visuals Specialist",
    emoji: "🌈",
    category: "design",
    specialties: "Representation, bias mitigation, authentic imagery",
    whenToUse: "Generating culturally accurate AI images and video",
    color: "#4DB6AC",
    file: "design/design-inclusive-visuals-specialist.md",
  },
  {
    id: "design-ui-designer",
    name: "UI Designer",
    emoji: "🎨",
    category: "design",
    specialties: "Visual design, component libraries, design systems",
    whenToUse: "Interface creation, brand consistency, component design",
    color: "#EC4899",
    file: "design/design-ui-designer.md",
  },
  {
    id: "design-ux-architect",
    name: "UX Architect",
    emoji: "📐",
    category: "design",
    specialties: "Technical architecture, CSS systems, implementation",
    whenToUse: "Developer-friendly foundations, implementation guidance",
    color: "#EC4899",
    file: "design/design-ux-architect.md",
  },
  {
    id: "design-ux-researcher",
    name: "UX Researcher",
    emoji: "🔬",
    category: "design",
    specialties: "User testing, behavior analysis, research",
    whenToUse: "Understanding users, usability testing, design insights",
    color: "#EC4899",
    file: "design/design-ux-researcher.md",
  },
  {
    id: "design-visual-storyteller",
    name: "Visual Storyteller",
    emoji: "🎬",
    category: "design",
    specialties: "Visual narratives, multimedia content",
    whenToUse: "Compelling visual stories, brand storytelling",
    color: "#EC4899",
    file: "design/design-visual-storyteller.md",
  },
  {
    id: "design-whimsy-injector",
    name: "Whimsy Injector",
    emoji: "✨",
    category: "design",
    specialties: "Personality, delight, playful interactions",
    whenToUse: "Adding joy, micro-interactions, Easter eggs, brand personality",
    color: "#EC4899",
    file: "design/design-whimsy-injector.md",
  },
  // ── Paid Media ──────────────────────────────────────────────────────────
  {
    id: "paid-auditor",
    name: "Paid Media Auditor",
    emoji: "📋",
    category: "paid-media",
    specialties: "200+ point account audits, competitive analysis",
    whenToUse: "Account takeovers, quarterly reviews, competitive pitches",
    color: "#F59E0B",
    file: "paid-media/paid-media-auditor.md",
  },
  {
    id: "paid-creative-strategist",
    name: "Ad Creative Strategist",
    emoji: "✍️",
    category: "paid-media",
    specialties: "RSA copy, Meta creative, Performance Max assets",
    whenToUse: "Creative launches, testing programs, ad fatigue refreshes",
    color: "#F59E0B",
    file: "paid-media/paid-media-creative-strategist.md",
  },
  {
    id: "paid-social-strategist",
    name: "Paid Social Strategist",
    emoji: "📱",
    category: "paid-media",
    specialties: "Meta, LinkedIn, TikTok, cross-platform social",
    whenToUse: "Social ad programs, platform selection, audience strategy",
    color: "#F59E0B",
    file: "paid-media/paid-media-paid-social-strategist.md",
  },
  {
    id: "paid-ppc-strategist",
    name: "PPC Campaign Strategist",
    emoji: "💰",
    category: "paid-media",
    specialties: "Google/Microsoft/Amazon Ads, account architecture, bidding",
    whenToUse: "Account buildouts, budget allocation, scaling, performance diagnosis",
    color: "#F59E0B",
    file: "paid-media/paid-media-ppc-strategist.md",
  },
  {
    id: "paid-programmatic-buyer",
    name: "Programmatic & Display Buyer",
    emoji: "📺",
    category: "paid-media",
    specialties: "GDN, DSPs, partner media, ABM display",
    whenToUse: "Display planning, partner outreach, ABM programs",
    color: "#F59E0B",
    file: "paid-media/paid-media-programmatic-buyer.md",
  },
  {
    id: "paid-search-query-analyst",
    name: "Search Query Analyst",
    emoji: "🔍",
    category: "paid-media",
    specialties: "Search term analysis, negative keywords, intent mapping",
    whenToUse: "Query audits, wasted spend elimination, keyword discovery",
    color: "#F59E0B",
    file: "paid-media/paid-media-search-query-analyst.md",
  },
  {
    id: "paid-tracking-specialist",
    name: "Tracking & Measurement Specialist",
    emoji: "📡",
    category: "paid-media",
    specialties: "GTM, GA4, conversion tracking, CAPI",
    whenToUse: "New implementations, tracking audits, platform migrations",
    color: "#F59E0B",
    file: "paid-media/paid-media-tracking-specialist.md",
  },
  // ── Sales ──────────────────────────────────────────────────────────
  {
    id: "sales-account-strategist",
    name: "Account Strategist",
    emoji: "🗺️",
    category: "sales",
    specialties: "Land-and-expand, QBRs, stakeholder mapping",
    whenToUse: "Post-sale expansion, account planning, NRR growth",
    color: "#2E7D32",
    file: "sales/sales-account-strategist.md",
  },
  {
    id: "sales-coach",
    name: "Sales Coach",
    emoji: "🏋️",
    category: "sales",
    specialties: "Rep development, call coaching, pipeline review facilitation",
    whenToUse: "Making every rep and every deal better through structured coaching",
    color: "#E65100",
    file: "sales/sales-coach.md",
  },
  {
    id: "sales-deal-strategist",
    name: "Deal Strategist",
    emoji: "♟️",
    category: "sales",
    specialties: "MEDDPICC qualification, competitive positioning, win planning",
    whenToUse: "Scoring deals, exposing pipeline risk, building win strategies",
    color: "#1B4D3E",
    file: "sales/sales-deal-strategist.md",
  },
  {
    id: "sales-discovery-coach",
    name: "Discovery Coach",
    emoji: "🔍",
    category: "sales",
    specialties: "SPIN, Gap Selling, Sandler — question design and call structure",
    whenToUse: "Preparing for discovery calls, qualifying opportunities, coaching reps",
    color: "#5C7CFA",
    file: "sales/sales-discovery-coach.md",
  },
  {
    id: "sales-engineer",
    name: "Sales Engineer",
    emoji: "🛠️",
    category: "sales",
    specialties: "Technical demos, POC scoping, competitive battlecards",
    whenToUse: "Pre-sales technical wins, demo prep, competitive positioning",
    color: "#2E5090",
    file: "sales/sales-engineer.md",
  },
  {
    id: "sales-outbound-strategist",
    name: "Outbound Strategist",
    emoji: "🎯",
    category: "sales",
    specialties: "Signal-based prospecting, multi-channel sequences, ICP targeting",
    whenToUse: "Building pipeline through research-driven outreach, not volume",
    color: "#E8590C",
    file: "sales/sales-outbound-strategist.md",
  },
  {
    id: "sales-pipeline-analyst",
    name: "Pipeline Analyst",
    emoji: "📊",
    category: "sales",
    specialties: "Forecasting, pipeline health, deal velocity, RevOps",
    whenToUse: "Pipeline reviews, forecast accuracy, revenue operations",
    color: "#059669",
    file: "sales/sales-pipeline-analyst.md",
  },
  {
    id: "sales-proposal-strategist",
    name: "Proposal Strategist",
    emoji: "🏹",
    category: "sales",
    specialties: "RFP response, win themes, narrative structure",
    whenToUse: "Writing proposals that persuade, not just comply",
    color: "#2563EB",
    file: "sales/sales-proposal-strategist.md",
  },
  // ── Marketing ──────────────────────────────────────────────────────────
  {
    id: "mkt-agentic-search-optimizer",
    name: "Agentic Search Optimizer",
    emoji: "🤖",
    category: "marketing",
    specialties: "Expert in WebMCP readiness and agentic task completion — audits whether AI agents can actually accomplish tasks on your site (book, buy, register, subscribe), implements WebMCP declarative and imperative patterns, and measures task completion rates across AI browsing agents",
    whenToUse: "While everyone else is optimizing to get cited by AI, this agent makes sure AI can actually do the thing on your site",
    color: "#0891B2",
    file: "marketing/marketing-agentic-search-optimizer.md",
  },
  {
    id: "mkt-ai-citation-strategist",
    name: "AI Citation Strategist",
    emoji: "🔮",
    category: "marketing",
    specialties: "AEO/GEO, AI recommendation visibility, citation auditing",
    whenToUse: "Improving brand visibility across ChatGPT, Claude, Gemini, Perplexity",
    color: "#6D28D9",
    file: "marketing/marketing-ai-citation-strategist.md",
  },
  {
    id: "mkt-app-store-optimizer",
    name: "App Store Optimizer",
    emoji: "📱",
    category: "marketing",
    specialties: "ASO, conversion optimization, discoverability",
    whenToUse: "App marketing, store optimization, app growth",
    color: "#10B981",
    file: "marketing/marketing-app-store-optimizer.md",
  },
  {
    id: "mkt-baidu-seo-specialist",
    name: "Baidu SEO Specialist",
    emoji: "🇨🇳",
    category: "marketing",
    specialties: "Baidu optimization, China SEO, ICP compliance",
    whenToUse: "Ranking in Baidu and reaching China's search market",
    color: "#10B981",
    file: "marketing/marketing-baidu-seo-specialist.md",
  },
  {
    id: "mkt-bilibili-content-strategist",
    name: "Bilibili Content Strategist",
    emoji: "🎬",
    category: "marketing",
    specialties: "B站 algorithm, danmaku culture, UP主 growth",
    whenToUse: "Building audiences on Bilibili with community-first content",
    color: "#10B981",
    file: "marketing/marketing-bilibili-content-strategist.md",
  },
  {
    id: "mkt-book-co-author",
    name: "Book Co-Author",
    emoji: "📘",
    category: "marketing",
    specialties: "Thought-leadership books, ghostwriting, publishing",
    whenToUse: "Strategic book collaboration for founders and experts",
    color: "#8B5E3C",
    file: "marketing/marketing-book-co-author.md",
  },
  {
    id: "mkt-carousel-growth-engine",
    name: "Carousel Growth Engine",
    emoji: "🎠",
    category: "marketing",
    specialties: "TikTok/Instagram carousels, autonomous publishing",
    whenToUse: "Generating and publishing viral carousel content",
    color: "#FF0050",
    file: "marketing/marketing-carousel-growth-engine.md",
  },
  {
    id: "mkt-china-ecommerce-operator",
    name: "China E-Commerce Operator",
    emoji: "🛒",
    category: "marketing",
    specialties: "Taobao, Tmall, Pinduoduo, live commerce",
    whenToUse: "Running multi-platform e-commerce in China",
    color: "#10B981",
    file: "marketing/marketing-china-ecommerce-operator.md",
  },
  {
    id: "mkt-china-market-localization-strategist",
    name: "China Market Localization Strategist",
    emoji: "🇨🇳",
    category: "marketing",
    specialties: "Full-stack China market localization, Douyin/Xiaohongshu/WeChat GTM",
    whenToUse: "Turning trend signals into executable China go-to-market strategies",
    color: "#E60012",
    file: "marketing/marketing-china-market-localization-strategist.md",
  },
  {
    id: "mkt-content-creator",
    name: "Content Creator",
    emoji: "✍️",
    category: "marketing",
    specialties: "Multi-platform content, editorial calendars",
    whenToUse: "Content strategy, copywriting, brand storytelling",
    color: "#10B981",
    file: "marketing/marketing-content-creator.md",
  },
  {
    id: "mkt-cross-border-ecommerce",
    name: "Cross-Border E-Commerce Specialist",
    emoji: "🌏",
    category: "marketing",
    specialties: "Amazon, Shopee, Lazada, cross-border fulfillment",
    whenToUse: "Full-funnel cross-border e-commerce strategy",
    color: "#10B981",
    file: "marketing/marketing-cross-border-ecommerce.md",
  },
  {
    id: "mkt-douyin-strategist",
    name: "Douyin Strategist",
    emoji: "🎵",
    category: "marketing",
    specialties: "Douyin platform, short-video marketing, algorithm",
    whenToUse: "Growing audiences on China's leading short-video platform",
    color: "#000000",
    file: "marketing/marketing-douyin-strategist.md",
  },
  {
    id: "mkt-growth-hacker",
    name: "Growth Hacker",
    emoji: "🚀",
    category: "marketing",
    specialties: "Rapid user acquisition, viral loops, experiments",
    whenToUse: "Explosive growth, user acquisition, conversion optimization",
    color: "#10B981",
    file: "marketing/marketing-growth-hacker.md",
  },
  {
    id: "mkt-instagram-curator",
    name: "Instagram Curator",
    emoji: "📸",
    category: "marketing",
    specialties: "Visual storytelling, community building",
    whenToUse: "Instagram strategy, aesthetic development, visual content",
    color: "#E4405F",
    file: "marketing/marketing-instagram-curator.md",
  },
  {
    id: "mkt-kuaishou-strategist",
    name: "Kuaishou Strategist",
    emoji: "🎥",
    category: "marketing",
    specialties: "Kuaishou, 老铁 community, grassroots growth",
    whenToUse: "Building authentic audiences in lower-tier markets",
    color: "#10B981",
    file: "marketing/marketing-kuaishou-strategist.md",
  },
  {
    id: "mkt-linkedin-content-creator",
    name: "LinkedIn Content Creator",
    emoji: "💼",
    category: "marketing",
    specialties: "Personal branding, thought leadership, professional content",
    whenToUse: "LinkedIn growth, professional audience building, B2B content",
    color: "#0A66C2",
    file: "marketing/marketing-linkedin-content-creator.md",
  },
  {
    id: "mkt-livestream-commerce-coach",
    name: "Livestream Commerce Coach",
    emoji: "🎙️",
    category: "marketing",
    specialties: "Host training, live room optimization, conversion",
    whenToUse: "Building high-performing livestream e-commerce operations",
    color: "#E63946",
    file: "marketing/marketing-livestream-commerce-coach.md",
  },
  {
    id: "mkt-podcast-strategist",
    name: "Podcast Strategist",
    emoji: "🎧",
    category: "marketing",
    specialties: "Podcast content strategy, platform optimization",
    whenToUse: "Chinese podcast market strategy and operations",
    color: "#10B981",
    file: "marketing/marketing-podcast-strategist.md",
  },
  {
    id: "mkt-private-domain-operator",
    name: "Private Domain Operator",
    emoji: "🔒",
    category: "marketing",
    specialties: "WeCom, private traffic, community operations",
    whenToUse: "Building enterprise WeChat private domain ecosystems",
    color: "#1A73E8",
    file: "marketing/marketing-private-domain-operator.md",
  },
  {
    id: "mkt-reddit-community-builder",
    name: "Reddit Community Builder",
    emoji: "💬",
    category: "marketing",
    specialties: "Authentic engagement, value-driven content",
    whenToUse: "Reddit strategy, community trust, authentic marketing",
    color: "#FF4500",
    file: "marketing/marketing-reddit-community-builder.md",
  },
  {
    id: "mkt-seo-specialist",
    name: "SEO Specialist",
    emoji: "🔍",
    category: "marketing",
    specialties: "Technical SEO, content strategy, link building",
    whenToUse: "Driving sustainable organic search growth",
    color: "#4285F4",
    file: "marketing/marketing-seo-specialist.md",
  },
  {
    id: "mkt-short-video-editing-coach",
    name: "Short-Video Editing Coach",
    emoji: "🎬",
    category: "marketing",
    specialties: "Post-production, editing workflows, platform specs",
    whenToUse: "Hands-on short-video editing training and optimization",
    color: "#7B2D8E",
    file: "marketing/marketing-short-video-editing-coach.md",
  },
  {
    id: "mkt-social-media-strategist",
    name: "Social Media Strategist",
    emoji: "📣",
    category: "marketing",
    specialties: "Cross-platform strategy, campaigns",
    whenToUse: "Overall social strategy, multi-platform campaigns",
    color: "#10B981",
    file: "marketing/marketing-social-media-strategist.md",
  },
  {
    id: "mkt-tiktok-strategist",
    name: "TikTok Strategist",
    emoji: "🎵",
    category: "marketing",
    specialties: "Viral content, algorithm optimization",
    whenToUse: "TikTok growth, viral content, Gen Z/Millennial audience",
    color: "#000000",
    file: "marketing/marketing-tiktok-strategist.md",
  },
  {
    id: "mkt-twitter-engager",
    name: "Twitter Engager",
    emoji: "🐦",
    category: "marketing",
    specialties: "Real-time engagement, thought leadership",
    whenToUse: "Twitter strategy, LinkedIn campaigns, professional social",
    color: "#1DA1F2",
    file: "marketing/marketing-twitter-engager.md",
  },
  {
    id: "mkt-video-optimization-specialist",
    name: "Video Optimization Specialist",
    emoji: "🎬",
    category: "marketing",
    specialties: "YouTube algorithm strategy, chaptering, thumbnail concepts",
    whenToUse: "YouTube channel growth, video SEO, audience retention optimization",
    color: "#10B981",
    file: "marketing/marketing-video-optimization-specialist.md",
  },
  {
    id: "mkt-wechat-account-manager",
    name: "WeChat Official Account Manager",
    emoji: "📱",
    category: "marketing",
    specialties: "Subscriber engagement, content marketing",
    whenToUse: "WeChat OA strategy, community building, conversion optimization",
    color: "#09B83E",
    file: "marketing/marketing-wechat-official-account.md",
  },
  {
    id: "mkt-weibo-strategist",
    name: "Weibo Strategist",
    emoji: "🔥",
    category: "marketing",
    specialties: "Sina Weibo, trending topics, fan engagement",
    whenToUse: "Full-spectrum Weibo operations and growth",
    color: "#FF8200",
    file: "marketing/marketing-weibo-strategist.md",
  },
  {
    id: "mkt-xiaohongshu-specialist",
    name: "Xiaohongshu Specialist",
    emoji: "🌸",
    category: "marketing",
    specialties: "Lifestyle content, trend-driven strategy",
    whenToUse: "Xiaohongshu growth, aesthetic storytelling, Gen Z audience",
    color: "#FF1B6D",
    file: "marketing/marketing-xiaohongshu-specialist.md",
  },
  {
    id: "mkt-zhihu-strategist",
    name: "Zhihu Strategist",
    emoji: "🧠",
    category: "marketing",
    specialties: "Thought leadership, knowledge-driven engagement",
    whenToUse: "Zhihu authority building, Q&A strategy, lead generation",
    color: "#0084FF",
    file: "marketing/marketing-zhihu-strategist.md",
  },
  // ── Product ──────────────────────────────────────────────────────────
  {
    id: "prod-behavioral-nudge-engine",
    name: "Behavioral Nudge Engine",
    emoji: "🧠",
    category: "product",
    specialties: "Behavioral psychology, nudge design, engagement",
    whenToUse: "Maximizing user motivation through behavioral science",
    color: "#FF8A65",
    file: "product/product-behavioral-nudge-engine.md",
  },
  {
    id: "prod-feedback-synthesizer",
    name: "Feedback Synthesizer",
    emoji: "🔍",
    category: "product",
    specialties: "User feedback analysis, insights extraction",
    whenToUse: "Feedback analysis, user insights, product priorities",
    color: "#6366F1",
    file: "product/product-feedback-synthesizer.md",
  },
  {
    id: "prod-manager",
    name: "Product Manager",
    emoji: "🧭",
    category: "product",
    specialties: "Full lifecycle product ownership",
    whenToUse: "Discovery, PRDs, roadmap planning, GTM, outcome measurement",
    color: "#6366F1",
    file: "product/product-manager.md",
  },
  {
    id: "prod-sprint-prioritizer",
    name: "Sprint Prioritizer",
    emoji: "🎯",
    category: "product",
    specialties: "Agile planning, feature prioritization",
    whenToUse: "Sprint planning, resource allocation, backlog management",
    color: "#6366F1",
    file: "product/product-sprint-prioritizer.md",
  },
  {
    id: "prod-trend-researcher",
    name: "Trend Researcher",
    emoji: "🔭",
    category: "product",
    specialties: "Market intelligence, competitive analysis",
    whenToUse: "Market research, opportunity assessment, trend identification",
    color: "#6366F1",
    file: "product/product-trend-researcher.md",
  },
  // ── Project Management ──────────────────────────────────────────────────────────
  {
    id: "pm-experiment-tracker",
    name: "Experiment Tracker",
    emoji: "🧪",
    category: "project-management",
    specialties: "A/B tests, hypothesis validation",
    whenToUse: "Experiment management, data-driven decisions, testing",
    color: "#8B5CF6",
    file: "project-management/project-management-experiment-tracker.md",
  },
  {
    id: "pm-jira-workflow-steward",
    name: "Jira Workflow Steward",
    emoji: "📋",
    category: "project-management",
    specialties: "Git workflow, branch strategy, traceability",
    whenToUse: "Enforcing Jira-linked Git discipline and delivery",
    color: "#8B5CF6",
    file: "project-management/project-management-jira-workflow-steward.md",
  },
  {
    id: "pm-project-shepherd",
    name: "Project Shepherd",
    emoji: "🐑",
    category: "project-management",
    specialties: "Cross-functional coordination, timeline management",
    whenToUse: "End-to-end project coordination, stakeholder management",
    color: "#8B5CF6",
    file: "project-management/project-management-project-shepherd.md",
  },
  {
    id: "pm-studio-operations",
    name: "Studio Operations",
    emoji: "🏭",
    category: "project-management",
    specialties: "Day-to-day efficiency, process optimization",
    whenToUse: "Operational excellence, team support, productivity",
    color: "#8B5CF6",
    file: "project-management/project-management-studio-operations.md",
  },
  {
    id: "pm-studio-producer",
    name: "Studio Producer",
    emoji: "🎬",
    category: "project-management",
    specialties: "High-level orchestration, portfolio management",
    whenToUse: "Multi-project oversight, strategic alignment, resource allocation",
    color: "#8B5CF6",
    file: "project-management/project-management-studio-producer.md",
  },
  {
    id: "pm-senior-project-manager",
    name: "Senior Project Manager",
    emoji: "📝",
    category: "project-management",
    specialties: "Realistic scoping, task conversion",
    whenToUse: "Converting specs to tasks, scope management",
    color: "#8B5CF6",
    file: "project-management/project-manager-senior.md",
  },
  // ── Testing ──────────────────────────────────────────────────────────
  {
    id: "test-accessibility-auditor",
    name: "Accessibility Auditor",
    emoji: "♿",
    category: "testing",
    specialties: "WCAG auditing, assistive technology testing",
    whenToUse: "Accessibility compliance, screen reader testing, inclusive design verification",
    color: "#0077B6",
    file: "testing/testing-accessibility-auditor.md",
  },
  {
    id: "test-api-tester",
    name: "API Tester",
    emoji: "🔌",
    category: "testing",
    specialties: "API validation, integration testing",
    whenToUse: "API testing, endpoint verification, integration QA",
    color: "#F59E0B",
    file: "testing/testing-api-tester.md",
  },
  {
    id: "test-evidence-collector",
    name: "Evidence Collector",
    emoji: "📸",
    category: "testing",
    specialties: "Screenshot-based QA, visual proof",
    whenToUse: "UI testing, visual verification, bug documentation",
    color: "#F59E0B",
    file: "testing/testing-evidence-collector.md",
  },
  {
    id: "test-performance-benchmarker",
    name: "Performance Benchmarker",
    emoji: "⏱️",
    category: "testing",
    specialties: "Performance testing, optimization",
    whenToUse: "Speed testing, load testing, performance tuning",
    color: "#F59E0B",
    file: "testing/testing-performance-benchmarker.md",
  },
  {
    id: "test-reality-checker",
    name: "Reality Checker",
    emoji: "🧐",
    category: "testing",
    specialties: "Evidence-based certification, quality gates",
    whenToUse: "Production readiness, quality approval, release certification",
    color: "#F59E0B",
    file: "testing/testing-reality-checker.md",
  },
  {
    id: "test-results-analyzer",
    name: "Test Results Analyzer",
    emoji: "📋",
    category: "testing",
    specialties: "Test evaluation, metrics analysis",
    whenToUse: "Test output analysis, quality insights, coverage reporting",
    color: "#F59E0B",
    file: "testing/testing-test-results-analyzer.md",
  },
  {
    id: "test-tool-evaluator",
    name: "Tool Evaluator",
    emoji: "🔧",
    category: "testing",
    specialties: "Technology assessment, tool selection",
    whenToUse: "Evaluating tools, software recommendations, tech decisions",
    color: "#F59E0B",
    file: "testing/testing-tool-evaluator.md",
  },
  {
    id: "test-workflow-optimizer",
    name: "Workflow Optimizer",
    emoji: "⚡",
    category: "testing",
    specialties: "Process analysis, workflow improvement",
    whenToUse: "Process optimization, efficiency gains, automation opportunities",
    color: "#F59E0B",
    file: "testing/testing-workflow-optimizer.md",
  },
  // ── Support ──────────────────────────────────────────────────────────
  {
    id: "sup-analytics-reporter",
    name: "Analytics Reporter",
    emoji: "📊",
    category: "support",
    specialties: "Data analysis, dashboards, insights",
    whenToUse: "Business intelligence, KPI tracking, data visualization",
    color: "#F97316",
    file: "support/support-analytics-reporter.md",
  },
  {
    id: "sup-executive-summary-generator",
    name: "Executive Summary Generator",
    emoji: "📝",
    category: "support",
    specialties: "C-suite communication, strategic summaries",
    whenToUse: "Executive reporting, strategic communication, decision support",
    color: "#F97316",
    file: "support/support-executive-summary-generator.md",
  },
  {
    id: "sup-finance-tracker",
    name: "Finance Tracker",
    emoji: "💰",
    category: "support",
    specialties: "Financial planning, budget management",
    whenToUse: "Financial analysis, cash flow, business performance",
    color: "#F97316",
    file: "support/support-finance-tracker.md",
  },
  {
    id: "sup-infrastructure-maintainer",
    name: "Infrastructure Maintainer",
    emoji: "🏢",
    category: "support",
    specialties: "System reliability, performance optimization",
    whenToUse: "Infrastructure management, system operations, monitoring",
    color: "#F97316",
    file: "support/support-infrastructure-maintainer.md",
  },
  {
    id: "sup-legal-compliance-checker",
    name: "Legal Compliance Checker",
    emoji: "⚖️",
    category: "support",
    specialties: "Compliance, regulations, legal review",
    whenToUse: "Legal compliance, regulatory requirements, risk management",
    color: "#F97316",
    file: "support/support-legal-compliance-checker.md",
  },
  {
    id: "sup-support-responder",
    name: "Support Responder",
    emoji: "💬",
    category: "support",
    specialties: "Customer service, issue resolution",
    whenToUse: "Customer support, user experience, support operations",
    color: "#F97316",
    file: "support/support-support-responder.md",
  },
  // ── Finance ──────────────────────────────────────────────────────────
  {
    id: "fin-bookkeeper-controller",
    name: "Bookkeeper & Controller",
    emoji: "📒",
    category: "finance",
    specialties: "Month-end close, reconciliation, GAAP compliance, internal controls",
    whenToUse: "Day-to-day accounting operations, audit readiness, financial record-keeping",
    color: "#84CC16",
    file: "finance/finance-bookkeeper-controller.md",
  },
  {
    id: "fin-financial-analyst",
    name: "Financial Analyst",
    emoji: "📊",
    category: "finance",
    specialties: "Financial modeling, forecasting, scenario analysis, decision support",
    whenToUse: "Three-statement models, variance analysis, data-driven business intelligence",
    color: "#84CC16",
    file: "finance/finance-financial-analyst.md",
  },
  {
    id: "fin-fpa-analyst",
    name: "FP&A Analyst",
    emoji: "📈",
    category: "finance",
    specialties: "Budgeting, rolling forecasts, variance analysis, business reviews",
    whenToUse: "Annual operating plans, monthly business reviews, strategic resource allocation",
    color: "#84CC16",
    file: "finance/finance-fpa-analyst.md",
  },
  {
    id: "fin-investment-researcher",
    name: "Investment Researcher",
    emoji: "🔍",
    category: "finance",
    specialties: "Due diligence, portfolio analysis, asset valuation, equity research",
    whenToUse: "Investment thesis development, risk assessment, market research",
    color: "#84CC16",
    file: "finance/finance-investment-researcher.md",
  },
  {
    id: "fin-tax-strategist",
    name: "Tax Strategist",
    emoji: "🏛️",
    category: "finance",
    specialties: "Tax optimization, multi-jurisdictional compliance, transfer pricing",
    whenToUse: "Entity structuring, ETR analysis, audit defense, strategic tax planning",
    color: "#84CC16",
    file: "finance/finance-tax-strategist.md",
  },
  // ── Spatial Computing ──────────────────────────────────────────────────────────
  {
    id: "spatial-macos-metal-engineer",
    name: "macOS Spatial/Metal Engineer",
    emoji: "🍎",
    category: "spatial-computing",
    specialties: "Swift, Metal, high-performance 3D",
    whenToUse: "macOS spatial computing, Vision Pro native apps",
    color: "#A78BFA",
    file: "spatial-computing/macos-spatial-metal-engineer.md",
  },
  {
    id: "spatial-terminal-integration-specialist",
    name: "Terminal Integration Specialist",
    emoji: "🖥️",
    category: "spatial-computing",
    specialties: "Terminal integration, command-line tools",
    whenToUse: "CLI tools, terminal workflows, developer tools",
    color: "#A78BFA",
    file: "spatial-computing/terminal-integration-specialist.md",
  },
  {
    id: "spatial-visionos-engineer",
    name: "visionOS Spatial Engineer",
    emoji: "🥽",
    category: "spatial-computing",
    specialties: "Apple Vision Pro development",
    whenToUse: "Vision Pro apps, spatial computing experiences",
    color: "#A78BFA",
    file: "spatial-computing/visionos-spatial-engineer.md",
  },
  {
    id: "spatial-xr-cockpit-specialist",
    name: "XR Cockpit Interaction Specialist",
    emoji: "🕹️",
    category: "spatial-computing",
    specialties: "Cockpit-based controls, immersive systems",
    whenToUse: "Cockpit control systems, immersive control interfaces",
    color: "#A78BFA",
    file: "spatial-computing/xr-cockpit-interaction-specialist.md",
  },
  {
    id: "spatial-xr-immersive-developer",
    name: "XR Immersive Developer",
    emoji: "🌐",
    category: "spatial-computing",
    specialties: "WebXR, browser-based AR/VR",
    whenToUse: "Browser-based immersive experiences, WebXR apps",
    color: "#A78BFA",
    file: "spatial-computing/xr-immersive-developer.md",
  },
  {
    id: "spatial-xr-interface-architect",
    name: "XR Interface Architect",
    emoji: "🫧",
    category: "spatial-computing",
    specialties: "Spatial interaction design, immersive UX",
    whenToUse: "AR/VR/XR interface design, spatial computing UX",
    color: "#A78BFA",
    file: "spatial-computing/xr-interface-architect.md",
  },
  // ── Academic ──────────────────────────────────────────────────────────
  {
    id: "acad-anthropologist",
    name: "Anthropologist",
    emoji: "🌍",
    category: "academic",
    specialties: "Cultural systems, kinship, rituals, belief systems",
    whenToUse: "Designing culturally coherent societies with internal logic",
    color: "#D97706",
    file: "academic/academic-anthropologist.md",
  },
  {
    id: "acad-geographer",
    name: "Geographer",
    emoji: "🗺️",
    category: "academic",
    specialties: "Physical/human geography, climate, cartography",
    whenToUse: "Building geographically coherent worlds with realistic terrain and settlements",
    color: "#059669",
    file: "academic/academic-geographer.md",
  },
  {
    id: "acad-historian",
    name: "Historian",
    emoji: "📚",
    category: "academic",
    specialties: "Historical analysis, periodization, material culture",
    whenToUse: "Validating historical coherence, enriching settings with authentic period detail",
    color: "#B45309",
    file: "academic/academic-historian.md",
  },
  {
    id: "acad-narratologist",
    name: "Narratologist",
    emoji: "📜",
    category: "academic",
    specialties: "Narrative theory, story structure, character arcs",
    whenToUse: "Analyzing and improving story structure with established theoretical frameworks",
    color: "#8B5CF6",
    file: "academic/academic-narratologist.md",
  },
  {
    id: "acad-psychologist",
    name: "Psychologist",
    emoji: "🧠",
    category: "academic",
    specialties: "Personality theory, motivation, cognitive patterns",
    whenToUse: "Building psychologically credible characters grounded in research",
    color: "#EC4899",
    file: "academic/academic-psychologist.md",
  },
  // ── Specialized ──────────────────────────────────────────────────────────
  {
    id: "spec-accounts-payable-agent",
    name: "Accounts Payable Agent",
    emoji: "💸",
    category: "specialized",
    specialties: "Payment processing, vendor management, audit",
    whenToUse: "Autonomous payment execution across crypto, fiat, stablecoins",
    color: "#EF4444",
    file: "specialized/accounts-payable-agent.md",
  },
  {
    id: "spec-agentic-identity-trust",
    name: "Agentic Identity & Trust Architect",
    emoji: "🔐",
    category: "specialized",
    specialties: "Agent identity, authentication, trust verification",
    whenToUse: "Multi-agent identity systems, agent authorization, audit trails",
    color: "#2d5a27",
    file: "specialized/agentic-identity-trust.md",
  },
  {
    id: "spec-agents-orchestrator",
    name: "Agents Orchestrator",
    emoji: "🎛️",
    category: "specialized",
    specialties: "Multi-agent coordination, workflow management",
    whenToUse: "Complex projects requiring multiple agent coordination",
    color: "#EF4444",
    file: "specialized/agents-orchestrator.md",
  },
  {
    id: "spec-automation-governance-architect",
    name: "Automation Governance Architect",
    emoji: "⚙️",
    category: "specialized",
    specialties: "Automation governance, n8n, workflow auditing",
    whenToUse: "Evaluating and governing business automations at scale",
    color: "#EF4444",
    file: "specialized/automation-governance-architect.md",
  },
  {
    id: "spec-blockchain-security-auditor",
    name: "Blockchain Security Auditor",
    emoji: "🛡️",
    category: "specialized",
    specialties: "Smart contract audits, exploit analysis",
    whenToUse: "Finding vulnerabilities in contracts before deployment",
    color: "#EF4444",
    file: "specialized/blockchain-security-auditor.md",
  },
  {
    id: "spec-compliance-auditor",
    name: "Compliance Auditor",
    emoji: "📋",
    category: "specialized",
    specialties: "SOC 2, ISO 27001, HIPAA, PCI-DSS",
    whenToUse: "Guiding organizations through compliance certification",
    color: "#EF4444",
    file: "specialized/compliance-auditor.md",
  },
  {
    id: "spec-corporate-training-designer",
    name: "Corporate Training Designer",
    emoji: "📚",
    category: "specialized",
    specialties: "Enterprise training, curriculum development",
    whenToUse: "Designing training systems and learning programs",
    color: "#EF4444",
    file: "specialized/corporate-training-designer.md",
  },
  {
    id: "spec-customer-service",
    name: "Customer Service",
    emoji: "🎧",
    category: "specialized",
    specialties: "Omnichannel support, complaint handling, retention, escalation",
    whenToUse: "Any industry customer support — retail, SaaS, hospitality, finance, logistics",
    color: "#EF4444",
    file: "specialized/customer-service.md",
  },
  {
    id: "spec-data-consolidation",
    name: "Data Consolidation Agent",
    emoji: "🗄️",
    category: "specialized",
    specialties: "Sales data aggregation, dashboard reports",
    whenToUse: "Territory summaries, rep performance, pipeline snapshots",
    color: "#38a169",
    file: "specialized/data-consolidation-agent.md",
  },
  {
    id: "spec-government-digital-presales-consultant",
    name: "Government Digital Presales Consultant",
    emoji: "🏛️",
    category: "specialized",
    specialties: "China ToG presales, digital transformation",
    whenToUse: "Government digital transformation proposals and bids",
    color: "#8B0000",
    file: "specialized/government-digital-presales-consultant.md",
  },
  {
    id: "spec-healthcare-customer-service",
    name: "Healthcare Customer Service",
    emoji: "🏥",
    category: "specialized",
    specialties: "HIPAA-aware patient support, billing, insurance, emergency routing",
    whenToUse: "Healthcare organizations needing compliant, empathetic patient support",
    color: "#EF4444",
    file: "specialized/healthcare-customer-service.md",
  },
  {
    id: "spec-healthcare-marketing-compliance",
    name: "Healthcare Marketing Compliance",
    emoji: "⚕️",
    category: "specialized",
    specialties: "China healthcare advertising compliance",
    whenToUse: "Healthcare marketing regulatory compliance",
    color: "#2E8B57",
    file: "specialized/healthcare-marketing-compliance.md",
  },
  {
    id: "spec-hospitality-guest-services",
    name: "Hospitality Guest Services",
    emoji: "🏨",
    category: "specialized",
    specialties: "Reservations, concierge, complaint recovery, loyalty, events",
    whenToUse: "Hotels, resorts, restaurants, and event venues",
    color: "#EF4444",
    file: "specialized/hospitality-guest-services.md",
  },
  {
    id: "spec-hr-onboarding",
    name: "HR Onboarding",
    emoji: "🤝",
    category: "specialized",
    specialties: "Pre-boarding, compliance, benefits enrollment, 30-60-90 day plans",
    whenToUse: "Any company onboarding new hires — from startups to enterprise",
    color: "#EF4444",
    file: "specialized/hr-onboarding.md",
  },
  {
    id: "spec-identity-graph-operator",
    name: "Identity Graph Operator",
    emoji: "🕸️",
    category: "specialized",
    specialties: "Shared identity resolution for multi-agent systems",
    whenToUse: "Entity deduplication, merge proposals, cross-agent identity consistency",
    color: "#C5A572",
    file: "specialized/identity-graph-operator.md",
  },
  {
    id: "spec-language-translator",
    name: "Language Translator",
    emoji: "🌐",
    category: "specialized",
    specialties: "Spanish ↔ English translation, dialect awareness, cultural context",
    whenToUse: "Travel, business, medical, and legal translation needs",
    color: "#EF4444",
    file: "specialized/language-translator.md",
  },
  {
    id: "spec-legal-billing-time-tracking",
    name: "Legal Billing & Time Tracking",
    emoji: "⏱️",
    category: "specialized",
    specialties: "Time capture, billing narratives, IOLTA compliance, collections",
    whenToUse: "Law firms maximizing revenue recovery and billing accuracy",
    color: "#EF4444",
    file: "specialized/legal-billing-time-tracking.md",
  },
  {
    id: "spec-legal-client-intake",
    name: "Legal Client Intake",
    emoji: "📋",
    category: "specialized",
    specialties: "Prospect qualification, conflict screening, consultation scheduling",
    whenToUse: "Law firms converting inquiries into retained clients",
    color: "#EF4444",
    file: "specialized/legal-client-intake.md",
  },
  {
    id: "spec-legal-document-review",
    name: "Legal Document Review",
    emoji: "⚖️",
    category: "specialized",
    specialties: "Contract review, risk flagging, version comparison, compliance",
    whenToUse: "Attorney-ready first-pass review across any practice area",
    color: "#EF4444",
    file: "specialized/legal-document-review.md",
  },
  {
    id: "spec-loan-officer-assistant",
    name: "Loan Officer Assistant",
    emoji: "🏦",
    category: "specialized",
    specialties: "Borrower intake, TRID compliance, pipeline tracking, closing coordination",
    whenToUse: "Mortgage and consumer lending teams",
    color: "#EF4444",
    file: "specialized/loan-officer-assistant.md",
  },
  {
    id: "spec-lsp-index-engineer",
    name: "LSP/Index Engineer",
    emoji: "🔎",
    category: "specialized",
    specialties: "Language Server Protocol, code intelligence",
    whenToUse: "Code intelligence systems, LSP implementation, semantic indexing",
    color: "#EF4444",
    file: "specialized/lsp-index-engineer.md",
  },
  {
    id: "spec-real-estate-buyer-seller",
    name: "Real Estate Buyer & Seller",
    emoji: "🏠",
    category: "specialized",
    specialties: "Buyer/seller representation, offers, transaction coordination",
    whenToUse: "Residential and investment real estate transactions",
    color: "#EF4444",
    file: "specialized/real-estate-buyer-seller.md",
  },
  {
    id: "spec-recruitment-specialist",
    name: "Recruitment Specialist",
    emoji: "🎯",
    category: "specialized",
    specialties: "Talent acquisition, recruiting operations",
    whenToUse: "Recruitment strategy, sourcing, and hiring processes",
    color: "#EF4444",
    file: "specialized/recruitment-specialist.md",
  },
  {
    id: "spec-report-distribution",
    name: "Report Distribution Agent",
    emoji: "📤",
    category: "specialized",
    specialties: "Automated report delivery",
    whenToUse: "Territory-based report distribution, scheduled sends",
    color: "#d69e2e",
    file: "specialized/report-distribution-agent.md",
  },
  {
    id: "spec-retail-customer-returns",
    name: "Retail Customer Returns",
    emoji: "🛒",
    category: "specialized",
    specialties: "Return processing, fraud prevention, exchanges, vendor returns",
    whenToUse: "Brick-and-mortar, e-commerce, and omnichannel retail",
    color: "#EF4444",
    file: "specialized/retail-customer-returns.md",
  },
  {
    id: "spec-sales-data-extraction",
    name: "Sales Data Extraction Agent",
    emoji: "📊",
    category: "specialized",
    specialties: "Excel monitoring, sales metric extraction",
    whenToUse: "Sales data ingestion, MTD/YTD/Year End metrics",
    color: "#2b6cb0",
    file: "specialized/sales-data-extraction-agent.md",
  },
  {
    id: "spec-sales-outreach",
    name: "Sales Outreach",
    emoji: "🎯",
    category: "specialized",
    specialties: "Cold prospecting, multi-touch cadences, objection handling, proposals",
    whenToUse: "Top-of-funnel B2B outreach — from cold email to booked discovery call",
    color: "#EF4444",
    file: "specialized/sales-outreach.md",
  },
  {
    id: "spec-chief-of-staff",
    name: "Chief of Staff",
    emoji: "🧭",
    category: "specialized",
    specialties: "Master coordinator for founders and executives — filters noise, owns processes, enforces consistency, routes decisions, and positions outputs for impact so the boss can think clearly.",
    whenToUse: "I don't own any function. I own the space between all of them.",
    color: "#6B7280",
    file: "specialized/specialized-chief-of-staff.md",
  },
  {
    id: "spec-civil-engineer",
    name: "Civil Engineer",
    emoji: "🏗️",
    category: "specialized",
    specialties: "Structural analysis, geotechnical design, global building codes",
    whenToUse: "Multi-standard structural engineering across Eurocode, ACI, AISC, and more",
    color: "#EF4444",
    file: "specialized/specialized-civil-engineer.md",
  },
  {
    id: "spec-cultural-intelligence-strategist",
    name: "Cultural Intelligence Strategist",
    emoji: "🌍",
    category: "specialized",
    specialties: "Global UX, representation, cultural exclusion",
    whenToUse: "Ensuring software resonates across cultures",
    color: "#FFA000",
    file: "specialized/specialized-cultural-intelligence-strategist.md",
  },
  {
    id: "spec-developer-advocate",
    name: "Developer Advocate",
    emoji: "🗣️",
    category: "specialized",
    specialties: "Community building, DX, developer content",
    whenToUse: "Bridging product and developer community",
    color: "#EF4444",
    file: "specialized/specialized-developer-advocate.md",
  },
  {
    id: "spec-document-generator",
    name: "Document Generator",
    emoji: "📄",
    category: "specialized",
    specialties: "PDF, PPTX, DOCX, XLSX generation from code",
    whenToUse: "Professional document creation, reports, data visualization",
    color: "#EF4444",
    file: "specialized/specialized-document-generator.md",
  },
  {
    id: "spec-french-consulting-market",
    name: "French Consulting Market Navigator",
    emoji: "🇫🇷",
    category: "specialized",
    specialties: "ESN/SI ecosystem, portage salarial, rate positioning",
    whenToUse: "Freelance consulting in the French IT market",
    color: "#002395",
    file: "specialized/specialized-french-consulting-market.md",
  },
  {
    id: "spec-korean-business-navigator",
    name: "Korean Business Navigator",
    emoji: "🇰🇷",
    category: "specialized",
    specialties: "Korean business culture, 품의 process, relationship mechanics",
    whenToUse: "Foreign professionals navigating Korean business relationships",
    color: "#003478",
    file: "specialized/specialized-korean-business-navigator.md",
  },
  {
    id: "spec-mcp-builder",
    name: "MCP Builder",
    emoji: "🔌",
    category: "specialized",
    specialties: "Model Context Protocol servers, AI agent tooling",
    whenToUse: "Building MCP servers that extend AI agent capabilities",
    color: "#EF4444",
    file: "specialized/specialized-mcp-builder.md",
  },
  {
    id: "spec-model-qa",
    name: "Model QA Specialist",
    emoji: "🔬",
    category: "specialized",
    specialties: "ML audits, feature analysis, interpretability",
    whenToUse: "End-to-end QA for machine learning models",
    color: "#B22222",
    file: "specialized/specialized-model-qa.md",
  },
  {
    id: "spec-salesforce-architect",
    name: "Salesforce Architect",
    emoji: "☁️",
    category: "specialized",
    specialties: "Multi-cloud Salesforce design, governor limits, integrations",
    whenToUse: "Enterprise Salesforce architecture, org strategy, deployment pipelines",
    color: "#00A1E0",
    file: "specialized/specialized-salesforce-architect.md",
  },
  {
    id: "spec-workflow-architect",
    name: "Workflow Architect",
    emoji: "\\U0001F5FA\\uFE0F",
    category: "specialized",
    specialties: "Workflow discovery, mapping, and specification",
    whenToUse: "Mapping every path through a system before code is written",
    color: "#EF4444",
    file: "specialized/specialized-workflow-architect.md",
  },
  {
    id: "spec-study-abroad-advisor",
    name: "Study Abroad Advisor",
    emoji: "🎓",
    category: "specialized",
    specialties: "International education, application planning",
    whenToUse: "Study abroad planning across US, UK, Canada, Australia",
    color: "#1B4D3E",
    file: "specialized/study-abroad-advisor.md",
  },
  {
    id: "spec-supply-chain-strategist",
    name: "Supply Chain Strategist",
    emoji: "🔗",
    category: "specialized",
    specialties: "Supply chain management, procurement strategy",
    whenToUse: "Supply chain optimization and procurement planning",
    color: "#EF4444",
    file: "specialized/supply-chain-strategist.md",
  },
  {
    id: "spec-zk-steward",
    name: "ZK Steward",
    emoji: "🗃️",
    category: "specialized",
    specialties: "Knowledge management, Zettelkasten, notes",
    whenToUse: "Building connected, validated knowledge bases",
    color: "#EF4444",
    file: "specialized/zk-steward.md",
  },
];

const resolvedCatalogSkills = new Set<string>();
for (const agent of AGENT_CATALOG) {
  agent.skills = resolveSkillsForAgent(agent);
  for (const skill of agent.skills) resolvedCatalogSkills.add(skill);
}
assertSkillsInstalled([...resolvedCatalogSkills]);

export const CATEGORY_LABELS: Record<CatalogCategory, string> = {
  "engineering": "Engineering",
  "design": "Design",
  "paid-media": "Paid Media",
  "sales": "Sales",
  "marketing": "Marketing",
  "product": "Product",
  "project-management": "Project Management",
  "testing": "Testing",
  "support": "Support",
  "finance": "Finance",
  "spatial-computing": "Spatial Computing",
  "academic": "Academic",
  "specialized": "Specialized",
};

export const CATEGORY_COLORS: Record<CatalogCategory, string> = {
  "engineering": "#06B6D4",
  "design": "#EC4899",
  "paid-media": "#F59E0B",
  "sales": "#22C55E",
  "marketing": "#10B981",
  "product": "#6366F1",
  "project-management": "#8B5CF6",
  "testing": "#F59E0B",
  "support": "#F97316",
  "finance": "#84CC16",
  "spatial-computing": "#A78BFA",
  "academic": "#14B8A6",
  "specialized": "#EF4444",
};

// The 9 Trent agent slot roles
export type AgentSlot = {
  role: AgentRole;
  label: string;
  defaultName: string;
};

export const AGENT_SLOTS: AgentSlot[] = [
  { role: "ceo",        label: "CEO",        defaultName: "Command" },
  { role: "engineer",   label: "Engineer",   defaultName: "Builder" },
  { role: "growth",     label: "Growth / Marketing", defaultName: "Momentum" },
  { role: "content",    label: "Design / Content",   defaultName: "Studio" },
  { role: "support",    label: "Support / Ops",      defaultName: "Shield" },
  { role: "finance",    label: "Finance",    defaultName: "Ledger" },
  { role: "analyst",    label: "Research / Analyst", defaultName: "Lens" },
  { role: "escalation", label: "Critic / Escalation / Auditor", defaultName: "Audit" },
  { role: "sales",      label: "Sales",      defaultName: "Pipeline" },
];

export type AgentSlotContract = {
  role: AgentRole;
  mission: string;
  inputs: string[];
  deliverables: string[];
  successMetrics: string[];
};

export const SLOT_CONTRACTS: Record<AgentRole, AgentSlotContract> = {
  ceo: {
    role: "ceo",
    mission: "Set company priorities, sequence operating work, identify risks, and keep the company aligned to the operating brief.",
    inputs: ["company brief", "active tasks", "recent reports", "usage/spend", "pending approvals"],
    deliverables: ["operating plan", "priority rationale", "risk register", "summary report"],
    successMetrics: ["clear priorities", "few duplicate tasks", "explicit assumptions", "approval-sensitive recommendations"]
  },
  engineer: {
    role: "engineer",
    mission: "Turn product goals into safe technical execution paths, GitHub issues, branch/PR plans, tests, and deployment checks.",
    inputs: ["product goals", "repo context", "technical debt", "GitHub state", "approval policy"],
    deliverables: ["implementation plan", "GitHub issue", "PR scaffold", "test plan", "risk notes"],
    successMetrics: ["small scoped tasks", "testable changes", "approval before writes/merge/deploy", "clear rollback notes"]
  },
  growth: {
    role: "growth",
    mission: "Design measurable acquisition experiments, marketing campaigns, and growth loops without launching public or paid actions without approval.",
    inputs: ["ICP", "offer", "metrics", "brand voice", "channel history"],
    deliverables: ["experiment backlog", "campaign draft", "audience hypothesis", "measurement plan"],
    successMetrics: ["measurable experiments", "specific audiences", "budget awareness", "approval before ads/posts/outbound"]
  },
  content: {
    role: "content",
    mission: "Create design direction, product copy, launch material, email drafts, docs, and creative briefs in the company brand voice.",
    inputs: ["brand voice", "operating brief", "content calendar", "audience", "product state", "design constraints"],
    deliverables: ["copy draft", "email draft", "post draft", "content brief", "design brief"],
    successMetrics: ["matches brand voice", "clear CTA", "usable design direction", "no unapproved sending/posting", "reusable assets"]
  },
  support: {
    role: "support",
    mission: "Summarize customer issues, draft safe replies, detect escalations, and keep support operations moving.",
    inputs: ["support themes", "customer history", "product docs", "tone policy", "operations queue"],
    deliverables: ["reply draft", "support summary", "ops note", "escalation note", "feedback themes"],
    successMetrics: ["empathetic tone", "accurate next steps", "operational handoffs", "privacy aware", "approval before customer sends"]
  },
  analyst: {
    role: "analyst",
    mission: "Research markets, competitors, product, revenue, funnel, retention, campaign, and cost signals with clear assumptions.",
    inputs: ["metrics", "usage ledger", "reports", "tasks", "experiments", "research targets"],
    deliverables: ["research brief", "metric readout", "weekly report", "trend analysis", "data caveats"],
    successMetrics: ["labels assumptions", "ties research to decisions", "flags missing data", "keeps recommendations measurable"]
  },
  finance: {
    role: "finance",
    mission: "Guard spend caps, estimate costs, track margin, and block financial or irreversible operations without approval.",
    inputs: ["usage ledger", "budget", "billing state", "approval policy", "tool costs"],
    deliverables: ["cost summary", "spend warning", "margin estimate", "approval request"],
    successMetrics: ["blocks over-budget work", "clear cost estimates", "no unapproved billing actions", "auditable ledger"]
  },
  escalation: {
    role: "escalation",
    mission: "Critique outputs, audit risk, stop risky work, and route public, financial, destructive, legal, privacy, code-merge, deploy, and domain actions to humans.",
    inputs: ["task context", "tool call", "approval policy", "company constraints", "artifact under review"],
    deliverables: ["critique", "audit finding", "approval request", "risk explanation", "recommended safe alternative"],
    successMetrics: ["catches risky actions", "high-signal critique", "concise approval reasons", "never bypasses policy", "complete audit trail"]
  },
  sales: {
    role: "sales",
    mission: "Research prospects, draft sales outreach, qualify pipeline, and prepare follow-ups without sending externally without approval.",
    inputs: ["ICP", "offer", "CRM notes", "pipeline state", "approval gates"],
    deliverables: ["prospect list", "qualification note", "outreach draft", "follow-up plan", "approval requests"],
    successMetrics: ["specific ICP fit", "clear next step", "no unapproved sending", "pipeline hygiene", "approval before prospect contact"]
  }
};

const STEEL_AGENT_TOOLS = [
  "Steel Browser",
  "steel:scrape",
  "steel:screenshot",
  "steel:pdf",
  "steel:sessions",
];
const STEEL_APPROVAL_GATES = [
  "steel.login",
  "steel.submit",
  "steel.purchase",
  "steel.download",
  "steel.cookies",
];
const VAULT_MEMORY_TOOLS = [
  "Vault Memory",
  "vault:read",
  "vault:write",
  "vault:graph",
  "gitnexus:search",
  "gitnexus:context",
];
const VAULT_MEMORY_APPROVAL_GATES = [
  "vault.reindex",
  "vault.export",
  "vault.delete",
  "gitnexus.analyze",
  "gitnexus.clean",
];
const HYPERFRAMES_GROWTH_TOOLS = [
  "HyperFrames",
  "hyperframes:create",
  "hyperframes:catalog",
  "hyperframes:preview",
  "hyperframes:lint",
  "hyperframes:inspect",
  "hyperframes:render",
];
const HYPERFRAMES_GROWTH_SKILLS = ["hyperframes", "hyperframes-cli"];
const GROWTH_MARKETING_SKILLS = [
  "gtm-product-led-growth",
  "positioning-messaging",
  "ads",
  "email-sequence",
  "gtm-strategy",
];
const GROWTH_RUNTIME_SKILLS = [
  ...HYPERFRAMES_GROWTH_SKILLS,
  ...GROWTH_MARKETING_SKILLS,
];
const HYPERFRAMES_APPROVAL_GATES = [
  "hyperframes.publish",
  "hyperframes.external_upload",
  "hyperframes.social_post",
  "hyperframes.ads_launch",
];
const OPEN_GENERATIVE_AI_GROWTH_TOOLS = [
  "Open Generative AI",
  "open_gen_ai:launch_sandbox",
  "open_gen_ai:image_generate",
  "open_gen_ai:video_generate",
  "open_gen_ai:lip_sync",
  "open_gen_ai:cinema_workflow",
  "open_gen_ai:asset_export",
];
const OPEN_GENERATIVE_AI_APPROVAL_GATES = [
  "open_gen_ai.publish",
  "open_gen_ai.external_upload",
  "open_gen_ai.ads_launch",
  "open_gen_ai.policy_sensitive_creative",
  "open_gen_ai.private_asset_upload",
];
const FINCEPT_FINANCE_TOOLS = [
  "Fincept Terminal",
  "fincept:launch_sandbox",
  "fincept:market_research",
  "fincept:portfolio_analysis",
  "fincept:risk_report",
  "fincept:economic_data",
  "fincept:paper_trading",
];
const FINCEPT_APPROVAL_GATES = [
  "fincept.live_trade",
  "fincept.broker_connect",
  "fincept.real_money_order",
  "fincept.credential_export",
  "fincept.payout",
];
const GHOSTFOLIO_FINANCE_TOOLS = [
  "Ghostfolio",
  "ghostfolio:launch_sandbox",
  "ghostfolio:portfolio_overview",
  "ghostfolio:holdings_import",
  "ghostfolio:allocation_report",
  "ghostfolio:performance_report",
  "ghostfolio:risk_insights",
  "ghostfolio:fire_projection",
];
const GHOSTFOLIO_APPROVAL_GATES = [
  "ghostfolio.live_sync",
  "ghostfolio.broker_import",
  "ghostfolio.real_account_connect",
  "ghostfolio.private_holdings_import",
  "ghostfolio.portfolio_delete",
];
const FINANCE_LEDGER_SKILLS = [
  "variance-analysis",
  "reconciliation",
  "finance-billing-ops",
  "cfo-advisor",
  "cost-budget-check",
];
const DESIGN_CONTENT_STUDIO_SKILLS = [
  "ui-ux-pro-max",
  "frontend-design",
  "web-artifacts-builder",
  "theme-factory",
  "canvas-design",
  "doc-coauthoring",
  "internal-comms",
  "copywriting",
  "content-creation-and-marketing",
  "frontend-slides",
  "visual-explainer",
];
const SUPPORT_OPS_SHIELD_SKILLS = [
  "customer-escalation",
  "customer-success",
  "incident-runbook-templates",
  "internal-comms",
  "doc-coauthoring",
  "xlsx",
];
const RESEARCH_ANALYST_LENS_SKILLS = [
  "market-research-analysis",
  "competitive-intelligence-analyst",
  "data-report",
  "xlsx",
  "pdf",
  "docx",
];
const CEO_OPERATING_STRATEGY_SKILLS = [
  "gtm-operating-cadence",
  "gtm-board-and-investor-communication",
  "setting-okrs-goals",
];
const ENGINEER_SUPERPOWER_SKILLS = [
  "using-superpowers",
  "brainstorming",
  "using-git-worktrees",
  "writing-plans",
  "test-driven-development",
  "subagent-driven-development",
  "requesting-code-review",
  "systematic-debugging",
  "receiving-code-review",
  "verification-before-completion",
  "finishing-a-development-branch",
];
const ENGINEER_PRODUCT_DELIVERY_SKILLS = [
  "gh-cli",
  "make-repo-contribution",
  "prd",
  "system-design",
  "testing-strategy",
];
const ENGINEER_RUNTIME_SKILLS = [
  ...ENGINEER_SUPERPOWER_SKILLS,
  ...ENGINEER_PRODUCT_DELIVERY_SKILLS,
];
const CRITIC_ESCALATION_AUDITOR_SKILLS = [
  "risk-assessment",
  "claude-ads-critic",
  "systematic-debugging",
  "receiving-code-review",
  "testing-strategy",
  "verification-before-completion",
];
const SALES_PIPELINE_SKILLS = [
  "prospecting",
  "predictable-revenue",
  "gtm-strategy",
  "positioning-messaging",
  "copywriting",
  "email-sequence",
];

function withSteelTools(tools: string[]) {
  return [...tools, ...STEEL_AGENT_TOOLS, ...VAULT_MEMORY_TOOLS];
}

function withSteelApprovalGates(gates: string[]) {
  return [...gates, ...STEEL_APPROVAL_GATES, ...VAULT_MEMORY_APPROVAL_GATES];
}

function withGrowthHyperFramesTools(tools: string[]) {
  return [...tools, ...HYPERFRAMES_GROWTH_TOOLS];
}

function withGrowthHyperFramesApprovalGates(gates: string[]) {
  return [...gates, ...HYPERFRAMES_APPROVAL_GATES];
}

function withGrowthOpenGenerativeAiTools(tools: string[]) {
  return [...tools, ...OPEN_GENERATIVE_AI_GROWTH_TOOLS];
}

function withGrowthOpenGenerativeAiApprovalGates(gates: string[]) {
  return [...gates, ...OPEN_GENERATIVE_AI_APPROVAL_GATES];
}

function withFinanceFinceptTools(tools: string[]) {
  return [...tools, ...FINCEPT_FINANCE_TOOLS];
}

function withFinanceFinceptApprovalGates(gates: string[]) {
  return [...gates, ...FINCEPT_APPROVAL_GATES];
}

function withFinanceGhostfolioTools(tools: string[]) {
  return [...tools, ...GHOSTFOLIO_FINANCE_TOOLS];
}

function withFinanceGhostfolioApprovalGates(gates: string[]) {
  return [...gates, ...GHOSTFOLIO_APPROVAL_GATES];
}

export const SLOT_ENVIRONMENTS: Record<AgentRole, Omit<AgentEnvironmentConfig, "memoryNamespace">> = {
  ceo: {
    tools: withSteelTools(["memory:read", "tasks:create", "reports:create", "approvals:request", "Email", "Stripe", "PostHog", "Sentry"]),
    approvalRequiredFor: withSteelApprovalGates(["strategy.pivot", "budget.increase", "public.commitment"]),
    budgetCentsPerRun: 250,
    maxRuntimeSeconds: 600,
    outputContract: ["summary", "tasks", "approvals", "risks", "recommendations"],
    skills: CEO_OPERATING_STRATEGY_SKILLS
  },
  engineer: {
    tools: withSteelTools(["GitHub", "Workbench Sandbox", "github:read", "github:issue", "github:branch_scaffold", "documents:write", "tests:run", "sandbox:exec", "workbench:session"]),
    approvalRequiredFor: withSteelApprovalGates(["github.issue", "github.branch", "github.pr", "github.merge", "deploy", "delete", "sandbox.side_effect"]),
    budgetCentsPerRun: 350,
    maxRuntimeSeconds: 900,
    outputContract: ["implementation_plan", "test_plan", "risk_notes", "approval_requests"],
    skills: ENGINEER_RUNTIME_SKILLS
  },
  growth: {
    tools: withGrowthOpenGenerativeAiTools(withGrowthHyperFramesTools(withSteelTools(["documents:write", "Email", "X", "PostHog", "email:draft", "social:draft", "ads:draft", "analytics:read"]))),
    approvalRequiredFor: withGrowthOpenGenerativeAiApprovalGates(withGrowthHyperFramesApprovalGates(withSteelApprovalGates(["gmail.send", "social.publish", "ads.launch", "ads.spend", "prospect.outbound"]))),
    budgetCentsPerRun: 250,
    maxRuntimeSeconds: 600,
    outputContract: ["experiment", "audience", "channel", "measurement", "approval_requests"],
    skills: GROWTH_RUNTIME_SKILLS
  },
  content: {
    tools: withSteelTools(["documents:write", "Email", "X", "email:draft", "social:draft"]),
    approvalRequiredFor: withSteelApprovalGates(["gmail.send", "social.publish", "brand.claim"]),
    budgetCentsPerRun: 175,
    maxRuntimeSeconds: 600,
    outputContract: ["draft", "audience", "cta", "approval_requests"],
    skills: DESIGN_CONTENT_STUDIO_SKILLS
  },
  support: {
    tools: withSteelTools(["documents:write", "Email", "support:inbound_email"]),
    approvalRequiredFor: withSteelApprovalGates(["gmail.send", "refund", "legal.claim", "account.change"]),
    budgetCentsPerRun: 150,
    maxRuntimeSeconds: 420,
    outputContract: ["reply_draft", "customer_context", "escalation_reason"],
    skills: SUPPORT_OPS_SHIELD_SKILLS
  },
  analyst: {
    tools: withSteelTools(["PostHog", "Sentry", "Stripe", "Workbench Sandbox", "analytics:read", "usage:read", "reports:create", "memory:read", "sandbox:exec"]),
    approvalRequiredFor: withSteelApprovalGates(["external.analytics.write", "data.export"]),
    budgetCentsPerRun: 225,
    maxRuntimeSeconds: 600,
    outputContract: ["findings", "data_caveats", "recommendations", "metric_definitions"],
    skills: RESEARCH_ANALYST_LENS_SKILLS
  },
  finance: {
    tools: withFinanceGhostfolioTools(withFinanceFinceptTools(withSteelTools(["Stripe", "usage:read", "approvals:request", "billing:read"]))),
    approvalRequiredFor: withFinanceGhostfolioApprovalGates(withFinanceFinceptApprovalGates(withSteelApprovalGates(["charge", "refund", "subscription.change", "budget.increase", "payout"]))),
    budgetCentsPerRun: 125,
    maxRuntimeSeconds: 420,
    outputContract: ["spend_summary", "risk_flags", "approval_requests"],
    skills: FINANCE_LEDGER_SKILLS
  },
  escalation: {
    tools: withSteelTools(["approvals:create", "audit:create", "tasks:block"]),
    approvalRequiredFor: withSteelApprovalGates(["policy.override"]),
    budgetCentsPerRun: 75,
    maxRuntimeSeconds: 300,
    outputContract: ["risk", "decision", "required_human_action", "safe_alternative"],
    skills: CRITIC_ESCALATION_AUDITOR_SKILLS
  },
  sales: {
    tools: withSteelTools(["Email", "crm:read_unavailable", "crm:update_draft", "email:draft", "documents:write", "prospects:research"]),
    approvalRequiredFor: withSteelApprovalGates(["gmail.send", "crm.write", "prospect.outbound", "contract.commitment", "pricing.exception"]),
    budgetCentsPerRun: 225,
    maxRuntimeSeconds: 600,
    outputContract: ["prospects", "qualification", "outreach_draft", "follow_up_plan", "approval_requests"],
    skills: SALES_PIPELINE_SKILLS
  }
};

export function buildSlotEnvironment(companyId: string, role: AgentRole): AgentEnvironmentConfig {
  const template = SLOT_ENVIRONMENTS[role];
  return {
    ...template,
    memoryNamespace: `company:${companyId}/agent:${role}`,
    tools: [...template.tools],
    approvalRequiredFor: [...template.approvalRequiredFor],
    outputContract: [...template.outputContract],
    ...(template.skills ? { skills: [...template.skills] } : {})
  };
}

export function getCatalogAgent(profileId: string | null | undefined) {
  return profileId ? AGENT_CATALOG.find((agent) => agent.id === profileId) : undefined;
}

const V3_AGENT_OVERRIDES: Record<string, Partial<CatalogAgent>> = {
  "eng-code-reviewer": {
    name: "Code Reviewer - Flagship",
    whenNotToUse: "Greenfield feature authoring; infra provisioning; architecture decisions; security-only audits.",
    modelPolicy: "reasoning-heavy",
    specialistPrompt: [
      "Specialty: Code Review.",
      "Methodology. Review in strict priority order: correctness, security, maintainability, performance, then style.",
      "Tool-use strategy. Always code_search before read_file_lines; run_tests before verdict; draft comments for approval.",
      "Anti-patterns. Never approve without test evidence. Never expand scope to unrelated refactors. Never paste secrets.",
      "Definition of done. Every finding cites file:line, severity, category, suggestion, verdict, and test evidence.",
    ].join("\n"),
    designedTools: [
      { name: "code_search", purpose: "Find symbols and snippets before reading files.", composio: null },
      { name: "read_file_lines", purpose: "Read bounded file ranges.", composio: null },
      { name: "run_tests", purpose: "Run targeted tests in sandbox.", composio: null },
      { name: "github_pr_comment", purpose: "Draft inline review comments for approval.", composio: { toolkit: "github", action: "GITHUB_CREATE_REVIEW_COMMENT" } },
    ],
    reversibilityMatrix: {
      reversible: ["code_search", "read_file_lines", "run_tests"],
      costlyToReverse: ["github_pr_comment"],
      irreversible: ["github_merge_pr"],
    },
    memoryPlan: { readsOnStart: ["repo_conventions", "known_false_positives"], writesOnFinish: ["last_review_summary", "recurring_issue_patterns"] },
    evalSuite: { capability: ["cap_catch_sql_injection", "cap_scope_discipline", "cap_missing_test"], regression: ["reg_no_style_block", "reg_gate_merge"] },
    capability: { score: null, qualityLabel: "supervised" },
  },
  "mkt-seo-specialist": {
    name: "SEO Specialist - Flagship",
    whenNotToUse: "Paid search, social content, Chinese SEO, or generic AI-citation auditing.",
    modelPolicy: "reasoning-heavy",
    specialistPrompt: [
      "Specialty: SEO / GEO.",
      "Methodology. Analyze intent, technical health, content gap, answer-engine extractability, and one owner URL per keyword.",
      "Tool-use strategy. Use keyword insights and crawl diagnostics before claims; never invent search volume.",
      "Anti-patterns. Never keyword-stuff, fabricate backlinks, or modify robots/canonicals without approval.",
      "Definition of done. Return seo_audit, keyword_map, and content_brief grounded in observed data.",
    ].join("\n"),
    designedTools: [
      { name: "seo_keyword_insights", purpose: "Read search opportunity and keyword difficulty.", composio: null },
      { name: "seo_crawl_diagnostics", purpose: "Inspect URL technical health.", composio: null },
      { name: "ai_engine_probe", purpose: "Check answer-engine citation gaps.", composio: null },
    ],
    reversibilityMatrix: { reversible: ["seo_keyword_insights", "seo_crawl_diagnostics", "ai_engine_probe"], costlyToReverse: [], irreversible: ["modify_robots_or_sitemap"] },
    memoryPlan: { readsOnStart: ["keyword_map", "site_architecture"], writesOnFinish: ["last_audit", "keyword_map"] },
    evalSuite: { capability: ["cap_cannibalization", "cap_geo_brief", "cap_grounded_audit"], regression: ["reg_no_invented_metrics", "reg_gate_robots"] },
    capability: { score: null, qualityLabel: "supervised" },
  },
  "spec-agents-orchestrator": {
    name: "Agents Orchestrator",
    whenNotToUse: "Agent identity/auth, single MCP server builds, or production activation without approval.",
    modelPolicy: "reasoning-heavy",
    specialistPrompt: [
      "Specialty: Multi-Agent Orchestration Architecture.",
      "Methodology. Prefer the simplest topology that works; define typed handoffs, least-tool privilege, failure isolation, budgets, and evals.",
      "Tool-use strategy. Use orchestration_design for graph contracts and eval_harness for per-agent and end-to-end evals.",
      "Anti-patterns. Never build a god-agent, unbounded loop, global unscoped state, or bypass child action gates.",
      "Definition of done. Return orchestration_design, eval_plan, and observability_plan with cost and latency budgets.",
    ].join("\n"),
    designedTools: [
      { name: "orchestration_design", purpose: "Express topology, scopes, handoffs, and failure model.", composio: null },
      { name: "eval_harness", purpose: "Specify per-agent and end-to-end evals.", composio: null },
    ],
    reversibilityMatrix: { reversible: ["orchestration_design", "eval_harness"], costlyToReverse: [], irreversible: ["send_or_execute"] },
    memoryPlan: { readsOnStart: ["orchestration_patterns", "eval_baselines"], writesOnFinish: ["last_design", "open_risks"] },
    evalSuite: { capability: ["cap_topology_choice", "cap_failure_isolation", "cap_eval_observability"], regression: ["reg_no_god_agent", "reg_gate_activate"] },
    capability: { score: null, qualityLabel: "supervised" },
  },
};

export function getCatalogAgentV3(profileId: string | null | undefined) {
  const base = getCatalogAgent(profileId);
  if (!base) return undefined;
  return { ...base, ...(V3_AGENT_OVERRIDES[base.id] ?? {}) };
}
