/**
 * T17.4 — Proactive Automations / Heartbeat System
 *
 * GET  /api/companies/:id/automations  — list suggestions generated by heartbeat scan
 * POST /api/companies/:id/automations  — run a heartbeat scan and generate suggestions
 * PATCH /api/companies/:id/automations — accept/snooze/reject a suggestion
 */

import { NextResponse } from "next/server";
import { store } from "@/lib/store";
import { getAuthUser, unauthorized, forbidden, requireRoleForRequest } from "@/lib/session";
import { nowIso } from "@/lib/utils";

// ── Heartbeat scanner ─────────────────────────────────────────────────────────

interface AutomationSuggestion {
  id: string;
  companyId: string;
  title: string;
  reason: string;
  schedule: string;
  requiredTools: string[];
  approvalPolicy: "always" | "first_run" | "never";
  estimatedCostCents: number;
  ownerSlot: string;
  status: "pending" | "accepted" | "snoozed" | "rejected";
  createdAt: string;
}

// In-memory store for suggestions (Phase 1 — move to DB in Phase 2)
const automationSuggestions = new Map<string, AutomationSuggestion[]>();

function getCompanySuggestions(companyId: string): AutomationSuggestion[] {
  return automationSuggestions.get(companyId) ?? [];
}

async function runHeartbeatScan(companyId: string): Promise<AutomationSuggestion[]> {
  const company = await store.getCompany(companyId);
  if (!company) return [];

  const [tasks, reports, cycles, approvals] = await Promise.all([
    store.listTasks(companyId),
    store.listReports(companyId),
    store.listCycles(companyId),
    store.listApprovals(companyId),
  ]);

  const existing = getCompanySuggestions(companyId).filter(s => s.status === "pending");
  const suggestions: AutomationSuggestion[] = [...existing];

  const makeId = () => `auto_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const now = nowIso();

  // Pattern: weekly reports are being generated manually
  const weeklyReports = reports.filter(r => r.type === "weekly");
  if (weeklyReports.length >= 1 && !suggestions.some(s => s.ownerSlot === "analyst" && s.title.includes("weekly"))) {
    suggestions.push({
      id: makeId(),
      companyId,
      title: "Automate weekly operating report",
      reason: `You've generated ${weeklyReports.length} weekly report${weeklyReports.length === 1 ? "" : "s"} manually. Trent can generate and deliver these every Sunday automatically.`,
      schedule: "every Sunday at 08:00 UTC",
      requiredTools: ["memory", "reports"],
      approvalPolicy: "never",
      estimatedCostCents: 20,
      ownerSlot: "analyst",
      status: "pending",
      createdAt: now,
    });
  }

  // Pattern: pending approvals are stacking up
  const pendingApprovals = approvals.filter(a => a.status === "pending");
  if (pendingApprovals.length >= 3 && !suggestions.some(s => s.title.includes("approval digest"))) {
    suggestions.push({
      id: makeId(),
      companyId,
      title: "Daily approval digest",
      reason: `You have ${pendingApprovals.length} pending approvals. A daily digest at a fixed time would prevent backlog.`,
      schedule: "every day at 09:00 UTC",
      requiredTools: ["email"],
      approvalPolicy: "first_run",
      estimatedCostCents: 5,
      ownerSlot: "ceo",
      status: "pending",
      createdAt: now,
    });
  }

  // Pattern: cycles are running but no nightly schedule set
  if (cycles.length >= 2 && company.nightlyRunHour === undefined && !suggestions.some(s => s.title.includes("nightly run"))) {
    suggestions.push({
      id: makeId(),
      companyId,
      title: "Enable nightly autonomous run",
      reason: `${company.name} has run ${cycles.length} cycles. Scheduling an overnight run would keep agents working while you sleep.`,
      schedule: "nightly at 02:00 UTC",
      requiredTools: ["scheduler"],
      approvalPolicy: "never",
      estimatedCostCents: 50,
      ownerSlot: "ceo",
      status: "pending",
      createdAt: now,
    });
  }

  // Pattern: engineer tasks waiting approval
  const engineerApprovals = tasks.filter(t => t.agentRole === "engineer" && t.status === "waiting_approval");
  if (engineerApprovals.length >= 2 && !suggestions.some(s => s.title.includes("PR review"))) {
    suggestions.push({
      id: makeId(),
      companyId,
      title: "Weekly PR review session",
      reason: `${engineerApprovals.length} engineer tasks are waiting for review. Block 30 min every Tuesday to review Trent's PR drafts.`,
      schedule: "every Tuesday at 10:00 UTC",
      requiredTools: ["github"],
      approvalPolicy: "always",
      estimatedCostCents: 0,
      ownerSlot: "engineer",
      status: "pending",
      createdAt: now,
    });
  }

  // Pattern: no growth tasks in the last 7 days
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
  const recentGrowthTasks = tasks.filter(t => t.agentRole === "growth" && t.createdAt >= sevenDaysAgo);
  if (recentGrowthTasks.length === 0 && cycles.length >= 3 && !suggestions.some(s => s.ownerSlot === "growth")) {
    suggestions.push({
      id: makeId(),
      companyId,
      title: "Weekly growth experiment",
      reason: "No growth tasks this week. A recurring prompt to run one growth experiment weekly keeps momentum.",
      schedule: "every Monday at 09:00 UTC",
      requiredTools: ["memory", "content"],
      approvalPolicy: "first_run",
      estimatedCostCents: 30,
      ownerSlot: "growth",
      status: "pending",
      createdAt: now,
    });
  }

  // Deduplicate by id, keeping latest version
  const seen = new Set<string>();
  const deduped = suggestions.filter(s => {
    if (seen.has(s.id)) return false;
    seen.add(s.id);
    return true;
  });

  automationSuggestions.set(companyId, deduped);
  return deduped.filter(s => s.status === "pending");
}

// ── Route handlers ────────────────────────────────────────────────────────────

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getAuthUser();
  if (!user) return unauthorized();

  const { id } = await params;
  const company = await store.getCompany(id);
  if (!company) return NextResponse.json({ error: "Company not found" }, { status: 404 });
  
  const check = await requireRoleForRequest(user.id, "viewer", { companyId: company.id });
  if (!check.ok) return forbidden();

  const suggestions = getCompanySuggestions(company.id).filter(s => s.status === "pending");
  return NextResponse.json({ suggestions });
}

export async function POST(_: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getAuthUser();
  if (!user) return unauthorized();

  const { id } = await params;
  const company = await store.getCompany(id);
  if (!company) return NextResponse.json({ error: "Company not found" }, { status: 404 });
  
  const check = await requireRoleForRequest(user.id, "admin", { companyId: company.id });
  if (!check.ok) return forbidden();

  const suggestions = await runHeartbeatScan(company.id);
  return NextResponse.json({ suggestions, scannedAt: nowIso() }, { status: 200 });
}

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getAuthUser();
  if (!user) return unauthorized();

  const { id } = await params;
  const company = await store.getCompany(id);
  if (!company) return NextResponse.json({ error: "Company not found" }, { status: 404 });
  
  const check = await requireRoleForRequest(user.id, "admin", { companyId: company.id });
  if (!check.ok) return forbidden();

  const { suggestionId, action } = await request.clone().json().catch(() => ({})) as {
    suggestionId: string;
    action: "accept" | "snooze" | "reject";
  };

  const all = getCompanySuggestions(company.id);
  const suggestion = all.find(s => s.id === suggestionId);
  if (!suggestion) return NextResponse.json({ error: "Suggestion not found" }, { status: 404 });

  const statusMap = { accept: "accepted", snooze: "snoozed", reject: "rejected" } as const;
  suggestion.status = statusMap[action] ?? "rejected";

  if (action === "accept") {
    // Create a recurring task template from the accepted suggestion
    const cadence: "weekly" | "daily" = suggestion.schedule.includes("week") ? "weekly" : "daily";
    const nextRunAt = new Date(Date.now() + (cadence === "weekly" ? 7 : 1) * 24 * 60 * 60 * 1000).toISOString();
    await store.createRecurringTask({
      companyId: company.id,
      title: suggestion.title,
      prompt: `[Proactive automation] ${suggestion.reason}\n\nSchedule: ${suggestion.schedule}`,
      agentRole: suggestion.ownerSlot as Parameters<typeof store.createRecurringTask>[0]["agentRole"],
      cadence,
      priority: "medium",
      enabled: true,
      tags: ["proactive", "heartbeat"],
      nextRunAt,
    });

    await store.addAudit(
      company.id,
      "user",
      "automation.accepted",
      "recurring_task",
      suggestion.id,
      `Accepted proactive automation: ${suggestion.title}`
    );
  }

  return NextResponse.json({ suggestion });
}
