import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  shell: { minHeight: "calc(100vh - 150px)", display: "grid", gap: 18 },
  leftRail: { minHeight: 720, display: "grid", gridTemplateRows: "auto 1fr auto auto", gap: 18, padding: 18, border: "1px solid rgba(255,255,255,.08)", borderRadius: 8, background: "linear-gradient(180deg, rgba(255,255,255,.045), rgba(255,255,255,.02))" },
  leftHeader: { borderBottom: "1px solid rgba(255,255,255,.07)", paddingBottom: 18 },
  title: { margin: "10px 0 10px", fontFamily: "var(--display)", fontSize: 40, lineHeight: .95, letterSpacing: 0, color: "var(--bone)" },
  lead: { margin: 0, color: "var(--mist)", lineHeight: 1.55, fontSize: 14 },
  agentStack: { display: "grid", alignContent: "start", gap: 8, overflow: "auto", paddingRight: 2 },
  agentButton: { minHeight: 58, display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", border: "1px solid rgba(255,255,255,.07)", borderRadius: 8, color: "var(--bone)", cursor: "pointer", textAlign: "left" },
  agentCode: { width: 34, height: 34, display: "inline-flex", alignItems: "center", justifyContent: "center", border: "1px solid rgba(110,231,183,.28)", color: "var(--pulse)", fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".12em" },
  agentName: { display: "block", fontWeight: 650, fontSize: 13 },
  agentMeta: { display: "block", marginTop: 3, color: "var(--haze)", fontFamily: "var(--mono)", fontSize: 9, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  activityPanel: { padding: 14, border: "1px solid rgba(255,255,255,.07)", borderRadius: 8, background: "rgba(10,10,15,.42)" },
  panelTitle: { fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".18em", textTransform: "uppercase", color: "var(--haze)", marginBottom: 12 },
  contractPanel: { display: "grid", gap: 7, padding: "0 0 12px", marginBottom: 10, borderBottom: "1px solid rgba(255,255,255,.06)" },
  contractTitle: { fontFamily: "var(--mono)", fontSize: 9, letterSpacing: ".16em", textTransform: "uppercase", color: "var(--pulse)" },
  contractRow: { display: "grid", gridTemplateColumns: "92px minmax(0, 1fr)", gap: 8, alignItems: "start", fontSize: 12, lineHeight: 1.35 },
  contractLabel: { fontFamily: "var(--mono)", fontSize: 9, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--haze)" },
  contractValue: { color: "var(--bone)", overflowWrap: "anywhere" },
  traceLine: { display: "flex", alignItems: "center", gap: 9, minHeight: 26, fontSize: 13 },
  traceDot: { width: 6, height: 6, borderRadius: 999, boxShadow: "0 0 18px rgba(110,231,183,.3)" },
  errorText: { marginTop: 10, color: "#FCA5A5", fontSize: 12, lineHeight: 1.45 },
  smallAction: { fontSize: 11 },
  traceLog: { marginTop: 10, display: "grid", gap: 3, maxHeight: 180, overflow: "auto", paddingTop: 8, borderTop: "1px solid rgba(255,255,255,.06)" },
  traceLogLine: { fontFamily: "var(--font-mono, monospace)", fontSize: 11, lineHeight: 1.5, color: "rgba(255,255,255,.62)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  promptDock: { display: "grid", gap: 10 },
  label: { fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".16em", color: "var(--haze)", textTransform: "uppercase" },
  textarea: { width: "100%", resize: "vertical", minHeight: 92, borderRadius: 8, border: "1px solid rgba(255,255,255,.08)", background: "rgba(255,255,255,.035)", color: "var(--bone)", padding: 12, lineHeight: 1.45 },
  segmentedControl: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 6 },
  segmentButton: { minHeight: 34, border: "1px solid rgba(255,255,255,.08)", borderRadius: 8, fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".08em", textTransform: "uppercase", cursor: "pointer" },
  stage: { minWidth: 0, border: "1px solid rgba(255,255,255,.08)", borderRadius: 8, overflow: "hidden", background: "rgba(255,255,255,.025)" },
  stageToolbar: { height: 54, display: "flex", alignItems: "center", gap: 12, padding: "0 14px", borderBottom: "1px solid rgba(255,255,255,.08)", background: "rgba(255,255,255,.035)" },
  windowDots: { display: "flex", gap: 7 },
  windowDot: { width: 9, height: 9, borderRadius: 999, background: "rgba(255,255,255,.18)" },
  pathBar: { minWidth: 0, flex: 1, height: 32, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, border: "1px solid rgba(255,255,255,.07)", borderRadius: 8, color: "var(--haze)", fontFamily: "var(--mono)", fontSize: 11 },
  heroSandbox: { position: "relative", minHeight: 666, padding: "42px min(5vw, 58px)", overflow: "hidden", background: "radial-gradient(circle at 78% 18%, rgba(110,231,183,.16), transparent 32%), linear-gradient(135deg, #0A0A0F 0%, #111116 52%, #090A0C 100%)" },
  previewShell: { position: "relative", minHeight: 560, display: "grid", border: "1px solid rgba(255,255,255,.12)", borderRadius: 8, overflow: "hidden", background: "rgba(255,255,255,.04)" },
  previewFrame: { width: "100%", minHeight: 560, border: 0, background: "#fff" },
  gridGlow: { position: "absolute", inset: 0, opacity: .18, backgroundImage: "linear-gradient(rgba(255,255,255,.06) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.06) 1px, transparent 1px)", backgroundSize: "48px 48px", maskImage: "linear-gradient(90deg, black, transparent 78%)" },
  stageTopline: { position: "relative", display: "flex", alignItems: "center", gap: 12, fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".22em", textTransform: "uppercase", color: "var(--pulse)", marginBottom: 52 },
  squareMark: { width: 34, height: 34, display: "inline-flex", alignItems: "center", justifyContent: "center", background: "var(--pulse)", color: "var(--obsidian)" },
  kicker: { position: "relative", display: "inline-flex", padding: "10px 14px", border: "1px solid rgba(110,231,183,.45)", color: "var(--pulse)", fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".18em", textTransform: "uppercase", marginBottom: 22 },
  stageTitle: { position: "relative", maxWidth: 820, margin: 0, fontFamily: "var(--display)", fontSize: "clamp(48px, 7vw, 104px)", lineHeight: .88, letterSpacing: 0, color: "var(--bone)" },
  stageCopy: { position: "relative", maxWidth: 720, margin: "24px 0 34px", color: "var(--bone-2)", fontSize: 17, lineHeight: 1.7 },
  appGrid: { position: "relative", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12, marginBottom: 32 },
  appCard: { minHeight: 138, padding: 16, textAlign: "left", border: "1px solid rgba(255,255,255,.08)", borderRadius: 8, background: "rgba(10,10,15,.68)", color: "var(--bone)", cursor: "pointer" },
  appLabel: { display: "block", fontFamily: "var(--mono)", fontSize: 9, letterSpacing: ".18em", textTransform: "uppercase", marginBottom: 14 },
  appName: { display: "block", fontSize: 18, fontWeight: 760, marginBottom: 8 },
  appDescription: { display: "block", color: "var(--mist)", fontSize: 12, lineHeight: 1.45 },
  scopeCount: { display: "inline-flex", marginTop: 12, fontFamily: "var(--mono)", fontSize: 9, letterSpacing: ".12em", textTransform: "uppercase", color: "var(--haze)" },
  outputBand: { position: "relative", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20, padding: 20, border: "1px solid rgba(255,255,255,.08)", borderRadius: 8, background: "rgba(255,255,255,.035)" },
  bandLabel: { fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".18em", textTransform: "uppercase", color: "var(--pulse)", marginBottom: 8 },
  bandTitle: { color: "var(--bone)", fontWeight: 650, lineHeight: 1.4 },
  bandActions: { display: "flex", gap: 10, flexWrap: "wrap", color: "var(--haze)", fontFamily: "var(--mono)", fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase" },
};
